// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ResolveResponse Returns the ResolverMetadata corresponding to the specified Id
//
// swagger:model v1alpha1ResolveResponse
type V1alpha1ResolveResponse struct {

	// The ResolverMetadata resolved from the Id
	ResolverMetadata *V1alpha1ResolverMetadata `json:"resolverMetadata,omitempty"`
}

// Validate validates this v1alpha1 resolve response
func (m *V1alpha1ResolveResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResolverMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ResolveResponse) validateResolverMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.ResolverMetadata) { // not required
		return nil
	}

	if m.ResolverMetadata != nil {
		if err := m.ResolverMetadata.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("resolverMetadata")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("resolverMetadata")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 resolve response based on the context it is used
func (m *V1alpha1ResolveResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResolverMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ResolveResponse) contextValidateResolverMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.ResolverMetadata != nil {

		if swag.IsZero(m.ResolverMetadata) { // not required
			return nil
		}

		if err := m.ResolverMetadata.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("resolverMetadata")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("resolverMetadata")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ResolveResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ResolveResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1ResolveResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
