// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1alpha1RegisterIssuerResponse Returns a registration response for the issuer
//
// swagger:model v1alpha1RegisterIssuerResponse
type V1alpha1RegisterIssuerResponse interface{}
