// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVcWellKnownParams creates a new GetVcWellKnownParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetVcWellKnownParams() *GetVcWellKnownParams {
	return &GetVcWellKnownParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetVcWellKnownParamsWithTimeout creates a new GetVcWellKnownParams object
// with the ability to set a timeout on a request.
func NewGetVcWellKnownParamsWithTimeout(timeout time.Duration) *GetVcWellKnownParams {
	return &GetVcWellKnownParams{
		timeout: timeout,
	}
}

// NewGetVcWellKnownParamsWithContext creates a new GetVcWellKnownParams object
// with the ability to set a context for a request.
func NewGetVcWellKnownParamsWithContext(ctx context.Context) *GetVcWellKnownParams {
	return &GetVcWellKnownParams{
		Context: ctx,
	}
}

// NewGetVcWellKnownParamsWithHTTPClient creates a new GetVcWellKnownParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetVcWellKnownParamsWithHTTPClient(client *http.Client) *GetVcWellKnownParams {
	return &GetVcWellKnownParams{
		HTTPClient: client,
	}
}

/*
GetVcWellKnownParams contains all the parameters to send to the API endpoint

	for the get vc well known operation.

	Typically these are written to a http.Request.
*/
type GetVcWellKnownParams struct {

	/* ID.

	   The identifier.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get vc well known params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVcWellKnownParams) WithDefaults() *GetVcWellKnownParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get vc well known params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVcWellKnownParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get vc well known params
func (o *GetVcWellKnownParams) WithTimeout(timeout time.Duration) *GetVcWellKnownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get vc well known params
func (o *GetVcWellKnownParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get vc well known params
func (o *GetVcWellKnownParams) WithContext(ctx context.Context) *GetVcWellKnownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get vc well known params
func (o *GetVcWellKnownParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get vc well known params
func (o *GetVcWellKnownParams) WithHTTPClient(client *http.Client) *GetVcWellKnownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get vc well known params
func (o *GetVcWellKnownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get vc well known params
func (o *GetVcWellKnownParams) WithID(id string) *GetVcWellKnownParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get vc well known params
func (o *GetVcWellKnownParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetVcWellKnownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
