// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// GetVcWellKnownReader is a Reader for the GetVcWellKnown structure.
type GetVcWellKnownReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVcWellKnownReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVcWellKnownOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetVcWellKnownDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVcWellKnownOK creates a GetVcWellKnownOK with default headers values
func NewGetVcWellKnownOK() *GetVcWellKnownOK {
	return &GetVcWellKnownOK{}
}

/*
GetVcWellKnownOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetVcWellKnownOK struct {
	Payload *models.V1alpha1GetVcWellKnownResponse
}

// IsSuccess returns true when this get vc well known o k response has a 2xx status code
func (o *GetVcWellKnownOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get vc well known o k response has a 3xx status code
func (o *GetVcWellKnownOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get vc well known o k response has a 4xx status code
func (o *GetVcWellKnownOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get vc well known o k response has a 5xx status code
func (o *GetVcWellKnownOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get vc well known o k response a status code equal to that given
func (o *GetVcWellKnownOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get vc well known o k response
func (o *GetVcWellKnownOK) Code() int {
	return 200
}

func (o *GetVcWellKnownOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/vc/{id}/.well-known/vcs.json][%d] getVcWellKnownOK %s", 200, payload)
}

func (o *GetVcWellKnownOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/vc/{id}/.well-known/vcs.json][%d] getVcWellKnownOK %s", 200, payload)
}

func (o *GetVcWellKnownOK) GetPayload() *models.V1alpha1GetVcWellKnownResponse {
	return o.Payload
}

func (o *GetVcWellKnownOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1GetVcWellKnownResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVcWellKnownDefault creates a GetVcWellKnownDefault with default headers values
func NewGetVcWellKnownDefault(code int) *GetVcWellKnownDefault {
	return &GetVcWellKnownDefault{
		_statusCode: code,
	}
}

/*
GetVcWellKnownDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetVcWellKnownDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get vc well known default response has a 2xx status code
func (o *GetVcWellKnownDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get vc well known default response has a 3xx status code
func (o *GetVcWellKnownDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get vc well known default response has a 4xx status code
func (o *GetVcWellKnownDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get vc well known default response has a 5xx status code
func (o *GetVcWellKnownDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get vc well known default response a status code equal to that given
func (o *GetVcWellKnownDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get vc well known default response
func (o *GetVcWellKnownDefault) Code() int {
	return o._statusCode
}

func (o *GetVcWellKnownDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/vc/{id}/.well-known/vcs.json][%d] GetVcWellKnown default %s", o._statusCode, payload)
}

func (o *GetVcWellKnownDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/vc/{id}/.well-known/vcs.json][%d] GetVcWellKnown default %s", o._statusCode, payload)
}

func (o *GetVcWellKnownDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetVcWellKnownDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
