// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// NewSearchVerifiableCredentialsParams creates a new SearchVerifiableCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchVerifiableCredentialsParams() *SearchVerifiableCredentialsParams {
	return &SearchVerifiableCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchVerifiableCredentialsParamsWithTimeout creates a new SearchVerifiableCredentialsParams object
// with the ability to set a timeout on a request.
func NewSearchVerifiableCredentialsParamsWithTimeout(timeout time.Duration) *SearchVerifiableCredentialsParams {
	return &SearchVerifiableCredentialsParams{
		timeout: timeout,
	}
}

// NewSearchVerifiableCredentialsParamsWithContext creates a new SearchVerifiableCredentialsParams object
// with the ability to set a context for a request.
func NewSearchVerifiableCredentialsParamsWithContext(ctx context.Context) *SearchVerifiableCredentialsParams {
	return &SearchVerifiableCredentialsParams{
		Context: ctx,
	}
}

// NewSearchVerifiableCredentialsParamsWithHTTPClient creates a new SearchVerifiableCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchVerifiableCredentialsParamsWithHTTPClient(client *http.Client) *SearchVerifiableCredentialsParams {
	return &SearchVerifiableCredentialsParams{
		HTTPClient: client,
	}
}

/*
SearchVerifiableCredentialsParams contains all the parameters to send to the API endpoint

	for the search verifiable credentials operation.

	Typically these are written to a http.Request.
*/
type SearchVerifiableCredentialsParams struct {

	// Body.
	Body *models.V1alpha1SearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search verifiable credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchVerifiableCredentialsParams) WithDefaults() *SearchVerifiableCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search verifiable credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchVerifiableCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) WithTimeout(timeout time.Duration) *SearchVerifiableCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) WithContext(ctx context.Context) *SearchVerifiableCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) WithHTTPClient(client *http.Client) *SearchVerifiableCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) WithBody(body *models.V1alpha1SearchRequest) *SearchVerifiableCredentialsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search verifiable credentials params
func (o *SearchVerifiableCredentialsParams) SetBody(body *models.V1alpha1SearchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchVerifiableCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
