// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// NewVerifyVerifiableCredentialParams creates a new VerifyVerifiableCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVerifyVerifiableCredentialParams() *VerifyVerifiableCredentialParams {
	return &VerifyVerifiableCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyVerifiableCredentialParamsWithTimeout creates a new VerifyVerifiableCredentialParams object
// with the ability to set a timeout on a request.
func NewVerifyVerifiableCredentialParamsWithTimeout(timeout time.Duration) *VerifyVerifiableCredentialParams {
	return &VerifyVerifiableCredentialParams{
		timeout: timeout,
	}
}

// NewVerifyVerifiableCredentialParamsWithContext creates a new VerifyVerifiableCredentialParams object
// with the ability to set a context for a request.
func NewVerifyVerifiableCredentialParamsWithContext(ctx context.Context) *VerifyVerifiableCredentialParams {
	return &VerifyVerifiableCredentialParams{
		Context: ctx,
	}
}

// NewVerifyVerifiableCredentialParamsWithHTTPClient creates a new VerifyVerifiableCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewVerifyVerifiableCredentialParamsWithHTTPClient(client *http.Client) *VerifyVerifiableCredentialParams {
	return &VerifyVerifiableCredentialParams{
		HTTPClient: client,
	}
}

/*
VerifyVerifiableCredentialParams contains all the parameters to send to the API endpoint

	for the verify verifiable credential operation.

	Typically these are written to a http.Request.
*/
type VerifyVerifiableCredentialParams struct {

	// Body.
	Body *models.V1alpha1VerifyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the verify verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyVerifiableCredentialParams) WithDefaults() *VerifyVerifiableCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the verify verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VerifyVerifiableCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) WithTimeout(timeout time.Duration) *VerifyVerifiableCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) WithContext(ctx context.Context) *VerifyVerifiableCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) WithHTTPClient(client *http.Client) *VerifyVerifiableCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) WithBody(body *models.V1alpha1VerifyRequest) *VerifyVerifiableCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the verify verifiable credential params
func (o *VerifyVerifiableCredentialParams) SetBody(body *models.V1alpha1VerifyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyVerifiableCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
