// Code generated by go-swagger; DO NOT EDIT.

package id_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// GenerateIDReader is a Reader for the GenerateID structure.
type GenerateIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGenerateIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGenerateIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGenerateIDOK creates a GenerateIDOK with default headers values
func NewGenerateIDOK() *GenerateIDOK {
	return &GenerateIDOK{}
}

/*
GenerateIDOK describes a response with status code 200, with default header values.

A successful response.
*/
type GenerateIDOK struct {
	Payload *models.V1alpha1GenerateResponse
}

// IsSuccess returns true when this generate Id o k response has a 2xx status code
func (o *GenerateIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this generate Id o k response has a 3xx status code
func (o *GenerateIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this generate Id o k response has a 4xx status code
func (o *GenerateIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this generate Id o k response has a 5xx status code
func (o *GenerateIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this generate Id o k response a status code equal to that given
func (o *GenerateIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the generate Id o k response
func (o *GenerateIDOK) Code() int {
	return 200
}

func (o *GenerateIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/id/generate][%d] generateIdOK %s", 200, payload)
}

func (o *GenerateIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/id/generate][%d] generateIdOK %s", 200, payload)
}

func (o *GenerateIDOK) GetPayload() *models.V1alpha1GenerateResponse {
	return o.Payload
}

func (o *GenerateIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1GenerateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateIDDefault creates a GenerateIDDefault with default headers values
func NewGenerateIDDefault(code int) *GenerateIDDefault {
	return &GenerateIDDefault{
		_statusCode: code,
	}
}

/*
GenerateIDDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GenerateIDDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this generate Id default response has a 2xx status code
func (o *GenerateIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this generate Id default response has a 3xx status code
func (o *GenerateIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this generate Id default response has a 4xx status code
func (o *GenerateIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this generate Id default response has a 5xx status code
func (o *GenerateIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this generate Id default response a status code equal to that given
func (o *GenerateIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the generate Id default response
func (o *GenerateIDDefault) Code() int {
	return o._statusCode
}

func (o *GenerateIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/id/generate][%d] GenerateId default %s", o._statusCode, payload)
}

func (o *GenerateIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/id/generate][%d] GenerateId default %s", o._statusCode, payload)
}

func (o *GenerateIDDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GenerateIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
