// Code generated by go-swagger; DO NOT EDIT.

package id_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new id service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for id service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GenerateID(params *GenerateIDParams, opts ...ClientOption) (*GenerateIDOK, error)

	ResolveID(params *ResolveIDParams, opts ...ClientOption) (*ResolveIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GenerateID generates an Id and its corresponding resolver metadata for a specified issuer
*/
func (a *Client) GenerateID(params *GenerateIDParams, opts ...ClientOption) (*GenerateIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGenerateIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GenerateId",
		Method:             "POST",
		PathPattern:        "/v1alpha1/id/generate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GenerateIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GenerateIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GenerateIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ResolveID resolves an Id to its corresponding resolver metadata
*/
func (a *Client) ResolveID(params *ResolveIDParams, opts ...ClientOption) (*ResolveIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewResolveIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ResolveId",
		Method:             "POST",
		PathPattern:        "/v1alpha1/id/resolve",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ResolveIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ResolveIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ResolveIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
