// Code generated by go-swagger; DO NOT EDIT.

package id_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// NewResolveIDParams creates a new ResolveIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResolveIDParams() *ResolveIDParams {
	return &ResolveIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResolveIDParamsWithTimeout creates a new ResolveIDParams object
// with the ability to set a timeout on a request.
func NewResolveIDParamsWithTimeout(timeout time.Duration) *ResolveIDParams {
	return &ResolveIDParams{
		timeout: timeout,
	}
}

// NewResolveIDParamsWithContext creates a new ResolveIDParams object
// with the ability to set a context for a request.
func NewResolveIDParamsWithContext(ctx context.Context) *ResolveIDParams {
	return &ResolveIDParams{
		Context: ctx,
	}
}

// NewResolveIDParamsWithHTTPClient creates a new ResolveIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewResolveIDParamsWithHTTPClient(client *http.Client) *ResolveIDParams {
	return &ResolveIDParams{
		HTTPClient: client,
	}
}

/*
ResolveIDParams contains all the parameters to send to the API endpoint

	for the resolve Id operation.

	Typically these are written to a http.Request.
*/
type ResolveIDParams struct {

	// Body.
	Body *models.V1alpha1ResolveRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resolve Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResolveIDParams) WithDefaults() *ResolveIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resolve Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResolveIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resolve Id params
func (o *ResolveIDParams) WithTimeout(timeout time.Duration) *ResolveIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resolve Id params
func (o *ResolveIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resolve Id params
func (o *ResolveIDParams) WithContext(ctx context.Context) *ResolveIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resolve Id params
func (o *ResolveIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resolve Id params
func (o *ResolveIDParams) WithHTTPClient(client *http.Client) *ResolveIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resolve Id params
func (o *ResolveIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the resolve Id params
func (o *ResolveIDParams) WithBody(body *models.V1alpha1ResolveRequest) *ResolveIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the resolve Id params
func (o *ResolveIDParams) SetBody(body *models.V1alpha1ResolveRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ResolveIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
