// Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/node/v1alpha1/vc_service.proto

package identity_node_sdk_go

import (
	v1alpha1 "github.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to publish an issued Verifiable Credential
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Verifiable Credential to publish
	Vc *v1alpha1.EnvelopedCredential `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	// Optional Proof of ownership of the Issuer's ResolverMetadata
	// This should be provided when the Issuer is provided by an external IdP
	// Example: a signed JWT
	Proof         *v1alpha1.Proof `protobuf:"bytes,2,opt,name=proof,proto3,oneof" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetVc() *v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vc
	}
	return nil
}

func (x *PublishRequest) GetProof() *v1alpha1.Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

// Request to verify an existing Verifiable Credential
type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Verifiable Credential to verify
	Vc            *v1alpha1.EnvelopedCredential `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyRequest) GetVc() *v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vc
	}
	return nil
}

// Request to search for VCs based on the specified criteria
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Schema is the schema of the credential contained in the VC
	Schema *v1alpha1.CredentialSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// The credential content representation in JSON-LD format
	Content       string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchRequest) GetSchema() *v1alpha1.CredentialSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SearchRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Returns the VCs that match the search criteria
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of VCs that match the search criteria
	Vcs           []*v1alpha1.EnvelopedCredential `protobuf:"bytes,1,rep,name=vcs,proto3" json:"vcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetVcs() []*v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vcs
	}
	return nil
}

// Requests the well-known VCs for an Id
type GetVcWellKnownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVcWellKnownRequest) Reset() {
	*x = GetVcWellKnownRequest{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVcWellKnownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVcWellKnownRequest) ProtoMessage() {}

func (x *GetVcWellKnownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVcWellKnownRequest.ProtoReflect.Descriptor instead.
func (*GetVcWellKnownRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetVcWellKnownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Returns the well-known VCs for an Id
type GetVcWellKnownResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of VCs for the specified Id
	Vcs           []*v1alpha1.EnvelopedCredential `protobuf:"bytes,1,rep,name=vcs,proto3" json:"vcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVcWellKnownResponse) Reset() {
	*x = GetVcWellKnownResponse{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVcWellKnownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVcWellKnownResponse) ProtoMessage() {}

func (x *GetVcWellKnownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVcWellKnownResponse.ProtoReflect.Descriptor instead.
func (*GetVcWellKnownResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetVcWellKnownResponse) GetVcs() []*v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vcs
	}
	return nil
}

// Request to revoke a published Verifiable Credential
type RevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Verifiable Credential to revoked
	Vc *v1alpha1.EnvelopedCredential `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	// Required Proof of ownership of the Issuer's ResolverMetadata
	// This should be provided when the Issuer is provided by an external IdP
	// Example: a signed JWT
	Proof         *v1alpha1.Proof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeRequest) GetVc() *v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vc
	}
	return nil
}

func (x *RevokeRequest) GetProof() *v1alpha1.Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_agntcy_identity_node_v1alpha1_vc_service_proto protoreflect.FileDescriptor

const file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDesc = "" +
	"\n" +
	".agntcy/identity/node/v1alpha1/vc_service.proto\x12\x1dagntcy.identity.node.v1alpha1\x1a&agntcy/identity/core/v1alpha1/vc.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9f\x01\n" +
	"\x0ePublishRequest\x12B\n" +
	"\x02vc\x18\x01 \x01(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x02vc\x12?\n" +
	"\x05proof\x18\x02 \x01(\v2$.agntcy.identity.core.v1alpha1.ProofH\x00R\x05proof\x88\x01\x01B\b\n" +
	"\x06_proof\"S\n" +
	"\rVerifyRequest\x12B\n" +
	"\x02vc\x18\x01 \x01(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x02vc\"\x82\x01\n" +
	"\rSearchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\x06schema\x18\x02 \x01(\v2/.agntcy.identity.core.v1alpha1.CredentialSchemaR\x06schema\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"V\n" +
	"\x0eSearchResponse\x12D\n" +
	"\x03vcs\x18\x01 \x03(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x03vcs\"'\n" +
	"\x15GetVcWellKnownRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x16GetVcWellKnownResponse\x12D\n" +
	"\x03vcs\x18\x01 \x03(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x03vcs\"\x8f\x01\n" +
	"\rRevokeRequest\x12B\n" +
	"\x02vc\x18\x01 \x01(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x02vc\x12:\n" +
	"\x05proof\x18\x02 \x01(\v2$.agntcy.identity.core.v1alpha1.ProofR\x05proof2\xc2\b\n" +
	"\tVcService\x12\xb2\x01\n" +
	"\aPublish\x12-.agntcy.identity.node.v1alpha1.PublishRequest\x1a\x16.google.protobuf.Empty\"`\x92A>\x12\x1fPublish a Verifiable Credential*\x1bPublishVerifiableCredential\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1alpha1/vc/publish\x12\xad\x01\n" +
	"\x06Verify\x12,.agntcy.identity.node.v1alpha1.VerifyRequest\x1a\x16.google.protobuf.Empty\"]\x92A<\x12\x1eVerify a Verifiable Credential*\x1aVerifyVerifiableCredential\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1alpha1/vc/verify\x12\x83\x02\n" +
	"\fGetWellKnown\x124.agntcy.identity.node.v1alpha1.GetVcWellKnownRequest\x1a5.agntcy.identity.node.v1alpha1.GetVcWellKnownResponse\"\x85\x01\x92AT\x12BReturns the well-known Verifiable Credentials for the specified Id*\x0eGetVcWellKnown\x82\xd3\xe4\x93\x02(\x12&/v1alpha1/vc/{id}/.well-known/vcs.json\x12\xe9\x01\n" +
	"\x06Search\x12,.agntcy.identity.node.v1alpha1.SearchRequest\x1a-.agntcy.identity.node.v1alpha1.SearchResponse\"\x81\x01\x92A`\x12ASearch for Verifiable Credentials based on the specified criteria*\x1bSearchVerifiableCredentials\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1alpha1/vc/search\x12\xcd\x01\n" +
	"\x06Revoke\x12,.agntcy.identity.node.v1alpha1.RevokeRequest\x1a\x16.google.protobuf.Empty\"}\x92A\\\x12>Revoke a Verifiable Credential. THIS ACTION IS NOT REVERSIBLE.*\x1aRevokeVerifiableCredential\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1alpha1/vc/revoke\x1a\x0e\x92A\v\n" +
	"\tVcServiceBZZXgithub.com/agntcy/identity/api/server/agntcy/identity/node/v1alpha1;identity_node_sdk_gob\x06proto3"

var (
	file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescOnce sync.Once
	file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescData []byte
)

func file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescGZIP() []byte {
	file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDesc), len(file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDesc)))
	})
	return file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDescData
}

var file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agntcy_identity_node_v1alpha1_vc_service_proto_goTypes = []any{
	(*PublishRequest)(nil),               // 0: agntcy.identity.node.v1alpha1.PublishRequest
	(*VerifyRequest)(nil),                // 1: agntcy.identity.node.v1alpha1.VerifyRequest
	(*SearchRequest)(nil),                // 2: agntcy.identity.node.v1alpha1.SearchRequest
	(*SearchResponse)(nil),               // 3: agntcy.identity.node.v1alpha1.SearchResponse
	(*GetVcWellKnownRequest)(nil),        // 4: agntcy.identity.node.v1alpha1.GetVcWellKnownRequest
	(*GetVcWellKnownResponse)(nil),       // 5: agntcy.identity.node.v1alpha1.GetVcWellKnownResponse
	(*RevokeRequest)(nil),                // 6: agntcy.identity.node.v1alpha1.RevokeRequest
	(*v1alpha1.EnvelopedCredential)(nil), // 7: agntcy.identity.core.v1alpha1.EnvelopedCredential
	(*v1alpha1.Proof)(nil),               // 8: agntcy.identity.core.v1alpha1.Proof
	(*v1alpha1.CredentialSchema)(nil),    // 9: agntcy.identity.core.v1alpha1.CredentialSchema
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
}
var file_agntcy_identity_node_v1alpha1_vc_service_proto_depIdxs = []int32{
	7,  // 0: agntcy.identity.node.v1alpha1.PublishRequest.vc:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	8,  // 1: agntcy.identity.node.v1alpha1.PublishRequest.proof:type_name -> agntcy.identity.core.v1alpha1.Proof
	7,  // 2: agntcy.identity.node.v1alpha1.VerifyRequest.vc:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	9,  // 3: agntcy.identity.node.v1alpha1.SearchRequest.schema:type_name -> agntcy.identity.core.v1alpha1.CredentialSchema
	7,  // 4: agntcy.identity.node.v1alpha1.SearchResponse.vcs:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	7,  // 5: agntcy.identity.node.v1alpha1.GetVcWellKnownResponse.vcs:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	7,  // 6: agntcy.identity.node.v1alpha1.RevokeRequest.vc:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	8,  // 7: agntcy.identity.node.v1alpha1.RevokeRequest.proof:type_name -> agntcy.identity.core.v1alpha1.Proof
	0,  // 8: agntcy.identity.node.v1alpha1.VcService.Publish:input_type -> agntcy.identity.node.v1alpha1.PublishRequest
	1,  // 9: agntcy.identity.node.v1alpha1.VcService.Verify:input_type -> agntcy.identity.node.v1alpha1.VerifyRequest
	4,  // 10: agntcy.identity.node.v1alpha1.VcService.GetWellKnown:input_type -> agntcy.identity.node.v1alpha1.GetVcWellKnownRequest
	2,  // 11: agntcy.identity.node.v1alpha1.VcService.Search:input_type -> agntcy.identity.node.v1alpha1.SearchRequest
	6,  // 12: agntcy.identity.node.v1alpha1.VcService.Revoke:input_type -> agntcy.identity.node.v1alpha1.RevokeRequest
	10, // 13: agntcy.identity.node.v1alpha1.VcService.Publish:output_type -> google.protobuf.Empty
	10, // 14: agntcy.identity.node.v1alpha1.VcService.Verify:output_type -> google.protobuf.Empty
	5,  // 15: agntcy.identity.node.v1alpha1.VcService.GetWellKnown:output_type -> agntcy.identity.node.v1alpha1.GetVcWellKnownResponse
	3,  // 16: agntcy.identity.node.v1alpha1.VcService.Search:output_type -> agntcy.identity.node.v1alpha1.SearchResponse
	10, // 17: agntcy.identity.node.v1alpha1.VcService.Revoke:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_agntcy_identity_node_v1alpha1_vc_service_proto_init() }
func file_agntcy_identity_node_v1alpha1_vc_service_proto_init() {
	if File_agntcy_identity_node_v1alpha1_vc_service_proto != nil {
		return
	}
	file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDesc), len(file_agntcy_identity_node_v1alpha1_vc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agntcy_identity_node_v1alpha1_vc_service_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_node_v1alpha1_vc_service_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_node_v1alpha1_vc_service_proto_msgTypes,
	}.Build()
	File_agntcy_identity_node_v1alpha1_vc_service_proto = out.File
	file_agntcy_identity_node_v1alpha1_vc_service_proto_goTypes = nil
	file_agntcy_identity_node_v1alpha1_vc_service_proto_depIdxs = nil
}
