// Code generated by "stringer -type=CredentialEnvelopeType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CREDENTIAL_ENVELOPE_TYPE_UNSPECIFIED-0]
	_ = x[CREDENTIAL_ENVELOPE_TYPE_EMBEDDED_PROOF-1]
	_ = x[CREDENTIAL_ENVELOPE_TYPE_JOSE-2]
}

const _CredentialEnvelopeType_name = "CREDENTIAL_ENVELOPE_TYPE_UNSPECIFIEDCREDENTIAL_ENVELOPE_TYPE_EMBEDDED_PROOFCREDENTIAL_ENVELOPE_TYPE_JOSE"

var _CredentialEnvelopeType_index = [...]uint8{0, 36, 75, 104}

func (i CredentialEnvelopeType) String() string {
	if i < 0 || i >= CredentialEnvelopeType(len(_CredentialEnvelopeType_index)-1) {
		return "CredentialEnvelopeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CredentialEnvelopeType_name[_CredentialEnvelopeType_index[i]:_CredentialEnvelopeType_index[i+1]]
}
