// Code generated by go-swagger; DO NOT EDIT.

package id_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// NewGenerateIDParams creates a new GenerateIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateIDParams() *GenerateIDParams {
	return &GenerateIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateIDParamsWithTimeout creates a new GenerateIDParams object
// with the ability to set a timeout on a request.
func NewGenerateIDParamsWithTimeout(timeout time.Duration) *GenerateIDParams {
	return &GenerateIDParams{
		timeout: timeout,
	}
}

// NewGenerateIDParamsWithContext creates a new GenerateIDParams object
// with the ability to set a context for a request.
func NewGenerateIDParamsWithContext(ctx context.Context) *GenerateIDParams {
	return &GenerateIDParams{
		Context: ctx,
	}
}

// NewGenerateIDParamsWithHTTPClient creates a new GenerateIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateIDParamsWithHTTPClient(client *http.Client) *GenerateIDParams {
	return &GenerateIDParams{
		HTTPClient: client,
	}
}

/*
GenerateIDParams contains all the parameters to send to the API endpoint

	for the generate Id operation.

	Typically these are written to a http.Request.
*/
type GenerateIDParams struct {

	// Body.
	Body *models.V1alpha1GenerateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateIDParams) WithDefaults() *GenerateIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate Id params
func (o *GenerateIDParams) WithTimeout(timeout time.Duration) *GenerateIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate Id params
func (o *GenerateIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate Id params
func (o *GenerateIDParams) WithContext(ctx context.Context) *GenerateIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate Id params
func (o *GenerateIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate Id params
func (o *GenerateIDParams) WithHTTPClient(client *http.Client) *GenerateIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate Id params
func (o *GenerateIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate Id params
func (o *GenerateIDParams) WithBody(body *models.V1alpha1GenerateRequest) *GenerateIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate Id params
func (o *GenerateIDParams) SetBody(body *models.V1alpha1GenerateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
