// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/core/v1alpha1/pagination.proto

package identity_core_sdk_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination response
type PagedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Next page
	NextPage *int32 `protobuf:"varint,1,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	// Has next page
	HasNextPage *bool `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3,oneof" json:"has_next_page,omitempty"`
	// The total size of items
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// The size of the current page
	Size          int32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagedResponse) Reset() {
	*x = PagedResponse{}
	mi := &file_agntcy_identity_core_v1alpha1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedResponse) ProtoMessage() {}

func (x *PagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_core_v1alpha1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedResponse.ProtoReflect.Descriptor instead.
func (*PagedResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PagedResponse) GetNextPage() int32 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

func (x *PagedResponse) GetHasNextPage() bool {
	if x != nil && x.HasNextPage != nil {
		return *x.HasNextPage
	}
	return false
}

func (x *PagedResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PagedResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_agntcy_identity_core_v1alpha1_pagination_proto protoreflect.FileDescriptor

const file_agntcy_identity_core_v1alpha1_pagination_proto_rawDesc = "" +
	"\n" +
	".agntcy/identity/core/v1alpha1/pagination.proto\x12\x1dagntcy.identity.core.v1alpha1\"\xa4\x01\n" +
	"\rPagedResponse\x12 \n" +
	"\tnext_page\x18\x01 \x01(\x05H\x00R\bnextPage\x88\x01\x01\x12'\n" +
	"\rhas_next_page\x18\x02 \x01(\bH\x01R\vhasNextPage\x88\x01\x01\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04sizeB\f\n" +
	"\n" +
	"_next_pageB\x10\n" +
	"\x0e_has_next_pageBSZQgithub.com/agntcy/identity/api/agntcy/identity/core/v1alpha1;identity_core_sdk_gob\x06proto3"

var (
	file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescOnce sync.Once
	file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescData []byte
)

func file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescGZIP() []byte {
	file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_pagination_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_pagination_proto_rawDesc)))
	})
	return file_agntcy_identity_core_v1alpha1_pagination_proto_rawDescData
}

var file_agntcy_identity_core_v1alpha1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agntcy_identity_core_v1alpha1_pagination_proto_goTypes = []any{
	(*PagedResponse)(nil), // 0: agntcy.identity.core.v1alpha1.PagedResponse
}
var file_agntcy_identity_core_v1alpha1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agntcy_identity_core_v1alpha1_pagination_proto_init() }
func file_agntcy_identity_core_v1alpha1_pagination_proto_init() {
	if File_agntcy_identity_core_v1alpha1_pagination_proto != nil {
		return
	}
	file_agntcy_identity_core_v1alpha1_pagination_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_pagination_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_identity_core_v1alpha1_pagination_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_core_v1alpha1_pagination_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_core_v1alpha1_pagination_proto_msgTypes,
	}.Build()
	File_agntcy_identity_core_v1alpha1_pagination_proto = out.File
	file_agntcy_identity_core_v1alpha1_pagination_proto_goTypes = nil
	file_agntcy_identity_core_v1alpha1_pagination_proto_depIdxs = nil
}
