// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1RegisterIssuerResponse Returns the action to take to complete the registration
//
// swagger:model v1alpha1RegisterIssuerResponse
type V1alpha1RegisterIssuerResponse struct {

	// Optional: a uri indicating an action to take to complete the registration
	// Depending on the issuer type, this could be a validation URL
	URI string `json:"uri,omitempty"`
}

// Validate validates this v1alpha1 register issuer response
func (m *V1alpha1RegisterIssuerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 register issuer response based on context it is used
func (m *V1alpha1RegisterIssuerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1RegisterIssuerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1RegisterIssuerResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1RegisterIssuerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
