// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1Service Service is used in ResolverMetadata to express ways of communicating with
// the node that published the document.
//
// swagger:model v1alpha1Service
type V1alpha1Service struct {

	// ServiceEndpoint is a network address, such as an HTTP URL, of the
	// node.
	ServiceEndpoint []string `json:"serviceEndpoint"`
}

// Validate validates this v1alpha1 service
func (m *V1alpha1Service) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 service based on context it is used
func (m *V1alpha1Service) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1Service) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1Service) UnmarshalBinary(b []byte) error {
	var res V1alpha1Service
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
