// Code generated by go-swagger; DO NOT EDIT.

package issuer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIssuerWellKnownParams creates a new GetIssuerWellKnownParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIssuerWellKnownParams() *GetIssuerWellKnownParams {
	return &GetIssuerWellKnownParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIssuerWellKnownParamsWithTimeout creates a new GetIssuerWellKnownParams object
// with the ability to set a timeout on a request.
func NewGetIssuerWellKnownParamsWithTimeout(timeout time.Duration) *GetIssuerWellKnownParams {
	return &GetIssuerWellKnownParams{
		timeout: timeout,
	}
}

// NewGetIssuerWellKnownParamsWithContext creates a new GetIssuerWellKnownParams object
// with the ability to set a context for a request.
func NewGetIssuerWellKnownParamsWithContext(ctx context.Context) *GetIssuerWellKnownParams {
	return &GetIssuerWellKnownParams{
		Context: ctx,
	}
}

// NewGetIssuerWellKnownParamsWithHTTPClient creates a new GetIssuerWellKnownParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIssuerWellKnownParamsWithHTTPClient(client *http.Client) *GetIssuerWellKnownParams {
	return &GetIssuerWellKnownParams{
		HTTPClient: client,
	}
}

/*
GetIssuerWellKnownParams contains all the parameters to send to the API endpoint

	for the get issuer well known operation.

	Typically these are written to a http.Request.
*/
type GetIssuerWellKnownParams struct {

	/* CommonName.

	   The common name of the issuer
	*/
	CommonName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get issuer well known params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIssuerWellKnownParams) WithDefaults() *GetIssuerWellKnownParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get issuer well known params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIssuerWellKnownParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get issuer well known params
func (o *GetIssuerWellKnownParams) WithTimeout(timeout time.Duration) *GetIssuerWellKnownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get issuer well known params
func (o *GetIssuerWellKnownParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get issuer well known params
func (o *GetIssuerWellKnownParams) WithContext(ctx context.Context) *GetIssuerWellKnownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get issuer well known params
func (o *GetIssuerWellKnownParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get issuer well known params
func (o *GetIssuerWellKnownParams) WithHTTPClient(client *http.Client) *GetIssuerWellKnownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get issuer well known params
func (o *GetIssuerWellKnownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommonName adds the commonName to the get issuer well known params
func (o *GetIssuerWellKnownParams) WithCommonName(commonName string) *GetIssuerWellKnownParams {
	o.SetCommonName(commonName)
	return o
}

// SetCommonName adds the commonName to the get issuer well known params
func (o *GetIssuerWellKnownParams) SetCommonName(commonName string) {
	o.CommonName = commonName
}

// WriteToRequest writes these params to a swagger request
func (o *GetIssuerWellKnownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param commonName
	if err := r.SetPathParam("commonName", o.CommonName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
