// Code generated by go-swagger; DO NOT EDIT.

package issuer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/sdk/node-go/models"
)

// NewRegisterIssuerParams creates a new RegisterIssuerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterIssuerParams() *RegisterIssuerParams {
	return &RegisterIssuerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterIssuerParamsWithTimeout creates a new RegisterIssuerParams object
// with the ability to set a timeout on a request.
func NewRegisterIssuerParamsWithTimeout(timeout time.Duration) *RegisterIssuerParams {
	return &RegisterIssuerParams{
		timeout: timeout,
	}
}

// NewRegisterIssuerParamsWithContext creates a new RegisterIssuerParams object
// with the ability to set a context for a request.
func NewRegisterIssuerParamsWithContext(ctx context.Context) *RegisterIssuerParams {
	return &RegisterIssuerParams{
		Context: ctx,
	}
}

// NewRegisterIssuerParamsWithHTTPClient creates a new RegisterIssuerParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterIssuerParamsWithHTTPClient(client *http.Client) *RegisterIssuerParams {
	return &RegisterIssuerParams{
		HTTPClient: client,
	}
}

/*
RegisterIssuerParams contains all the parameters to send to the API endpoint

	for the register issuer operation.

	Typically these are written to a http.Request.
*/
type RegisterIssuerParams struct {

	// Body.
	Body *models.V1alpha1RegisterIssuerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register issuer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterIssuerParams) WithDefaults() *RegisterIssuerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register issuer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterIssuerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register issuer params
func (o *RegisterIssuerParams) WithTimeout(timeout time.Duration) *RegisterIssuerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register issuer params
func (o *RegisterIssuerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register issuer params
func (o *RegisterIssuerParams) WithContext(ctx context.Context) *RegisterIssuerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register issuer params
func (o *RegisterIssuerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register issuer params
func (o *RegisterIssuerParams) WithHTTPClient(client *http.Client) *RegisterIssuerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register issuer params
func (o *RegisterIssuerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register issuer params
func (o *RegisterIssuerParams) WithBody(body *models.V1alpha1RegisterIssuerRequest) *RegisterIssuerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register issuer params
func (o *RegisterIssuerParams) SetBody(body *models.V1alpha1RegisterIssuerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterIssuerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
