// Code generated by "stringer -type=CredentialStatusPurpose"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CREDENTIAL_STATUS_PURPOSE_UNSPECIFIED-0]
	_ = x[CREDENTIAL_STATUS_PURPOSE_REVOCATION-1]
}

const _CredentialStatusPurpose_name = "CREDENTIAL_STATUS_PURPOSE_UNSPECIFIEDCREDENTIAL_STATUS_PURPOSE_REVOCATION"

var _CredentialStatusPurpose_index = [...]uint8{0, 37, 73}

func (i CredentialStatusPurpose) String() string {
	if i < 0 || i >= CredentialStatusPurpose(len(_CredentialStatusPurpose_index)-1) {
		return "CredentialStatusPurpose(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CredentialStatusPurpose_name[_CredentialStatusPurpose_index[i]:_CredentialStatusPurpose_index[i+1]]
}
