// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1VerifyRequest Request to verify an existing Verifiable Credential
//
// swagger:model v1alpha1VerifyRequest
type V1alpha1VerifyRequest struct {

	// The Verifiable Credential to verify
	Vc *V1alpha1EnvelopedCredential `json:"vc,omitempty"`
}

// Validate validates this v1alpha1 verify request
func (m *V1alpha1VerifyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVc(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1VerifyRequest) validateVc(formats strfmt.Registry) error {
	if swag.IsZero(m.Vc) { // not required
		return nil
	}

	if m.Vc != nil {
		if err := m.Vc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vc")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 verify request based on the context it is used
func (m *V1alpha1VerifyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1VerifyRequest) contextValidateVc(ctx context.Context, formats strfmt.Registry) error {

	if m.Vc != nil {

		if swag.IsZero(m.Vc) { // not required
			return nil
		}

		if err := m.Vc.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vc")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1VerifyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1VerifyRequest) UnmarshalBinary(b []byte) error {
	var res V1alpha1VerifyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
