// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1EnvelopedCredential EnvelopedCredential represents a Credential enveloped in a specific format.
//
// swagger:model v1alpha1EnvelopedCredential
type V1alpha1EnvelopedCredential struct {

	// EnvelopeType specifies the type of the envelope used to store the credential.
	EnvelopeType *V1alpha1CredentialEnvelopeType `json:"envelopeType,omitempty"`

	// Value is the enveloped credential in the specified format.
	Value string `json:"value,omitempty"`
}

// Validate validates this v1alpha1 enveloped credential
func (m *V1alpha1EnvelopedCredential) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnvelopeType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1EnvelopedCredential) validateEnvelopeType(formats strfmt.Registry) error {
	if swag.IsZero(m.EnvelopeType) { // not required
		return nil
	}

	if m.EnvelopeType != nil {
		if err := m.EnvelopeType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("envelopeType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("envelopeType")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 enveloped credential based on the context it is used
func (m *V1alpha1EnvelopedCredential) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnvelopeType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1EnvelopedCredential) contextValidateEnvelopeType(ctx context.Context, formats strfmt.Registry) error {

	if m.EnvelopeType != nil {

		if swag.IsZero(m.EnvelopeType) { // not required
			return nil
		}

		if err := m.EnvelopeType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("envelopeType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("envelopeType")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1EnvelopedCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1EnvelopedCredential) UnmarshalBinary(b []byte) error {
	var res V1alpha1EnvelopedCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
