// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1CredentialSchema CredentialSchema represents the credentialSchema property of a Verifiable Credential.
// more information can be found [here]
//
// swagger:model v1alpha1CredentialSchema
//
// [here]: https://www.w3.org/TR/vc-data-model-2.0/#data-schemas
type V1alpha1CredentialSchema struct {

	// The URL identifying the schema file
	ID string `json:"id,omitempty"`

	// Type specifies the type of the file
	Type string `json:"type,omitempty"`
}

// Validate validates this v1alpha1 credential schema
func (m *V1alpha1CredentialSchema) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 credential schema based on context it is used
func (m *V1alpha1CredentialSchema) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1CredentialSchema) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1CredentialSchema) UnmarshalBinary(b []byte) error {
	var res V1alpha1CredentialSchema
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
