// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SearchResponse Returns the VCs that match the search criteria
//
// swagger:model v1alpha1SearchResponse
type V1alpha1SearchResponse struct {

	// The list of VCs that match the search criteria
	Vcs []*V1alpha1EnvelopedCredential `json:"vcs"`
}

// Validate validates this v1alpha1 search response
func (m *V1alpha1SearchResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVcs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1SearchResponse) validateVcs(formats strfmt.Registry) error {
	if swag.IsZero(m.Vcs) { // not required
		return nil
	}

	for i := 0; i < len(m.Vcs); i++ {
		if swag.IsZero(m.Vcs[i]) { // not required
			continue
		}

		if m.Vcs[i] != nil {
			if err := m.Vcs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vcs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("vcs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1alpha1 search response based on the context it is used
func (m *V1alpha1SearchResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVcs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1SearchResponse) contextValidateVcs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Vcs); i++ {

		if m.Vcs[i] != nil {

			if swag.IsZero(m.Vcs[i]) { // not required
				return nil
			}

			if err := m.Vcs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vcs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("vcs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SearchResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SearchResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1SearchResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
