// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1Proof A data integrity proof provides information about the proof mechanism,
// parameters required to verify that proof, and the proof value itself.
//
// swagger:model v1alpha1Proof
type V1alpha1Proof struct {

	// The proof purpose
	ProofPurpose string `json:"proofPurpose,omitempty"`

	// The proof value
	ProofValue string `json:"proofValue,omitempty"`

	// The type of the proof
	Type string `json:"type,omitempty"`
}

// Validate validates this v1alpha1 proof
func (m *V1alpha1Proof) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 proof based on context it is used
func (m *V1alpha1Proof) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1Proof) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1Proof) UnmarshalBinary(b []byte) error {
	var res V1alpha1Proof
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
