# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agntcy.identity.node.v1alpha1 import id_service_pb2 as agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2


class IdServiceStub(object):
    """IdService is the service that provides ID operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.IdService/Generate',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.IdService/Resolve',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveRequest.SerializeToString,
                response_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveResponse.FromString,
                _registered_method=True)


class IdServiceServicer(object):
    """IdService is the service that provides ID operations.
    """

    def Generate(self, request, context):
        """Generate an Id and its corresponding ResolverMetadata for the specified Issuer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Resolve a specified Id to its corresponding ResolverMetadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateRequest.FromString,
                    response_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateResponse.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveRequest.FromString,
                    response_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agntcy.identity.node.v1alpha1.IdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agntcy.identity.node.v1alpha1.IdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdService(object):
    """IdService is the service that provides ID operations.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.IdService/Generate',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateRequest.SerializeToString,
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.IdService/Resolve',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveRequest.SerializeToString,
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_id__service__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
