# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/node/v1alpha1/issuer_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agntcy.identity.core.v1alpha1 import issuer_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_issuer__pb2
from agntcy.identity.core.v1alpha1 import jwk_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_jwk__pb2
from agntcy.identity.core.v1alpha1 import vc_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2agntcy/identity/node/v1alpha1/issuer_service.proto\x12\x1d\x61gntcy.identity.node.v1alpha1\x1a*agntcy/identity/core/v1alpha1/issuer.proto\x1a\'agntcy/identity/core/v1alpha1/jwk.proto\x1a&agntcy/identity/core/v1alpha1/vc.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa1\x01\n\x15RegisterIssuerRequest\x12=\n\x06issuer\x18\x01 \x01(\x0b\x32%.agntcy.identity.core.v1alpha1.IssuerR\x06issuer\x12?\n\x05proof\x18\x02 \x01(\x0b\x32$.agntcy.identity.core.v1alpha1.ProofH\x00R\x05proof\x88\x01\x01\x42\x08\n\x06_proof\"\x18\n\x16RegisterIssuerResponse\"<\n\x19GetIssuerWellKnownRequest\x12\x1f\n\x0b\x63ommon_name\x18\x01 \x01(\tR\ncommonName\"U\n\x1aGetIssuerWellKnownResponse\x12\x37\n\x04jwks\x18\x01 \x01(\x0b\x32#.agntcy.identity.core.v1alpha1.JwksR\x04jwks2\xb7\x04\n\rIssuerService\x12\xe4\x01\n\x08Register\x12\x34.agntcy.identity.node.v1alpha1.RegisterIssuerRequest\x1a\x35.agntcy.identity.node.v1alpha1.RegisterIssuerResponse\"k\x92\x41\x44\x12\x32Register an issuer by providing the issuer details*\x0eRegisterIssuer\x82\xd3\xe4\x93\x02\x1e\"\x19/v1alpha1/issuer/register:\x01*\x12\xaa\x02\n\x0cGetWellKnown\x12\x38.agntcy.identity.node.v1alpha1.GetIssuerWellKnownRequest\x1a\x39.agntcy.identity.node.v1alpha1.GetIssuerWellKnownResponse\"\xa4\x01\x92\x41\x65\x12OReturns the well-known document for an issuer in Json Web Key Set (JWKS) format*\x12GetIssuerWellKnown\x82\xd3\xe4\x93\x02\x36\x12\x34/v1alpha1/issuer/{common_name}/.well-known/jwks.json\x1a\x12\x92\x41\x0f\n\rIssuerServiceB\xa8\x02\n!com.agntcy.identity.node.v1alpha1B\x12IssuerServiceProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/node/v1alpha1;identity_node_sdk_go\xa2\x02\x03\x41IN\xaa\x02\x1d\x41gntcy.Identity.Node.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Node\\V1alpha1\xe2\x02)Agntcy\\Identity\\Node\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Node::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.node.v1alpha1.issuer_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.node.v1alpha1B\022IssuerServiceProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/node/v1alpha1;identity_node_sdk_go\242\002\003AIN\252\002\035Agntcy.Identity.Node.V1alpha1\312\002\035Agntcy\\Identity\\Node\\V1alpha1\342\002)Agntcy\\Identity\\Node\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Node::V1alpha1'
  _globals['_ISSUERSERVICE']._options = None
  _globals['_ISSUERSERVICE']._serialized_options = b'\222A\017\n\rIssuerService'
  _globals['_ISSUERSERVICE'].methods_by_name['Register']._options = None
  _globals['_ISSUERSERVICE'].methods_by_name['Register']._serialized_options = b'\222AD\0222Register an issuer by providing the issuer details*\016RegisterIssuer\202\323\344\223\002\036\"\031/v1alpha1/issuer/register:\001*'
  _globals['_ISSUERSERVICE'].methods_by_name['GetWellKnown']._options = None
  _globals['_ISSUERSERVICE'].methods_by_name['GetWellKnown']._serialized_options = b'\222Ae\022OReturns the well-known document for an issuer in Json Web Key Set (JWKS) format*\022GetIssuerWellKnown\202\323\344\223\0026\0224/v1alpha1/issuer/{common_name}/.well-known/jwks.json'
  _globals['_REGISTERISSUERREQUEST']._serialized_start=289
  _globals['_REGISTERISSUERREQUEST']._serialized_end=450
  _globals['_REGISTERISSUERRESPONSE']._serialized_start=452
  _globals['_REGISTERISSUERRESPONSE']._serialized_end=476
  _globals['_GETISSUERWELLKNOWNREQUEST']._serialized_start=478
  _globals['_GETISSUERWELLKNOWNREQUEST']._serialized_end=538
  _globals['_GETISSUERWELLKNOWNRESPONSE']._serialized_start=540
  _globals['_GETISSUERWELLKNOWNRESPONSE']._serialized_end=625
  _globals['_ISSUERSERVICE']._serialized_start=628
  _globals['_ISSUERSERVICE']._serialized_end=1195
# @@protoc_insertion_point(module_scope)
