# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/node/v1alpha1/openapi.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openapiv3 import annotations_pb2 as openapiv3_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+agntcy/identity/node/v1alpha1/openapi.proto\x12\x1d\x61gntcy.identity.node.v1alpha1\x1a\x1bopenapiv3/annotations.protoB\xcc\x03\n!com.agntcy.identity.node.v1alpha1B\x0cOpenapiProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/node/v1alpha1;identity_node_sdk_go\xa2\x02\x03\x41IN\xaa\x02\x1d\x41gntcy.Identity.Node.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Node\\V1alpha1\xe2\x02)Agntcy\\Identity\\Node\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Node::V1alpha1\xbaG\xa6\x01\x12p\n\rIdentity Node\x12\rIdentity Node\"F\n\x0b\x41gntcy Team\x12\"https://github.com/agntcy/identity\x1a\x13identity@agntcy.org2\x08v1alpha1\x1a(\n\x13http://0.0.0.0:4000\x12\x11Local environment*\x06\x32\x02\n\x00:\x00\x32\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.node.v1alpha1.openapi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.node.v1alpha1B\014OpenapiProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/node/v1alpha1;identity_node_sdk_go\242\002\003AIN\252\002\035Agntcy.Identity.Node.V1alpha1\312\002\035Agntcy\\Identity\\Node\\V1alpha1\342\002)Agntcy\\Identity\\Node\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Node::V1alpha1\272G\246\001\022p\n\rIdentity Node\022\rIdentity Node\"F\n\013Agntcy Team\022\"https://github.com/agntcy/identity\032\023identity@agntcy.org2\010v1alpha1\032(\n\023http://0.0.0.0:4000\022\021Local environment*\0062\002\n\000:\0002\000'
# @@protoc_insertion_point(module_scope)
