# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agntcy.identity.core.v1alpha1 import vc_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2
from agntcy.identity.node.v1alpha1 import vc_service_pb2 as agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class VcServiceStub(object):
    """VC is the service that provides VC operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.VcService/Publish',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.PublishRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.VcService/Verify',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.VerifyRequest.SerializeToString,
                response_deserializer=agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2.VerificationResult.FromString,
                _registered_method=True)
        self.GetWellKnown = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.VcService/GetWellKnown',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownRequest.SerializeToString,
                response_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.VcService/Search',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/agntcy.identity.node.v1alpha1.VcService/Revoke',
                request_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.RevokeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VcServiceServicer(object):
    """VC is the service that provides VC operations.
    """

    def Publish(self, request, context):
        """Publish an issued Verifiable Credential
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Verify an existing Verifiable Credential
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWellKnown(self, request, context):
        """Returns the well-known Verifiable Credentials for the specified Id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for Verifiable Credentials based on the specified criteria
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Revoke a Verifiable Credential. THIS ACTION IS NOT REVERSIBLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.PublishRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.VerifyRequest.FromString,
                    response_serializer=agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2.VerificationResult.SerializeToString,
            ),
            'GetWellKnown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWellKnown,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownRequest.FromString,
                    response_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchRequest.FromString,
                    response_serializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.RevokeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agntcy.identity.node.v1alpha1.VcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agntcy.identity.node.v1alpha1.VcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VcService(object):
    """VC is the service that provides VC operations.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.VcService/Publish',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.PublishRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.VcService/Verify',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.VerifyRequest.SerializeToString,
            agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2.VerificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWellKnown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.VcService/GetWellKnown',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownRequest.SerializeToString,
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.GetVcWellKnownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.VcService/Search',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchRequest.SerializeToString,
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.identity.node.v1alpha1.VcService/Revoke',
            agntcy_dot_identity_dot_node_dot_v1alpha1_dot_vc__service__pb2.RevokeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
