# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

FROM python:3.12-slim

WORKDIR /code
COPY ./* .
RUN pip install .

CMD ["python", "main.py"]
