// This file was autogenerated by go-to-protobuf. Do not edit it manually!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/core/v1alpha1/issuer.proto

package identity_core_sdk_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IssuerAuthType represents the type of authentication mechanism used by the issuer.
type IssuerAuthType int32

const (
	// ISSUER_AUTH_TYPE_UNSPECIFIED represents an unspecified or unknown authentication type.
	IssuerAuthType_ISSUER_AUTH_TYPE_UNSPECIFIED IssuerAuthType = 0
	// ISSUER_AUTH_TYPE_IDP indicates that the issuer uses an external Identity Provider (IDP)
	// to authenticate
	IssuerAuthType_ISSUER_AUTH_TYPE_IDP IssuerAuthType = 1
	// ISSUER_AUTH_TYPE_SELF indicates that the issuer uses a self-issued key for authentication.
	// This is typically used in scenarios where the issuer doesn't rely on an IdP.
	IssuerAuthType_ISSUER_AUTH_TYPE_SELF IssuerAuthType = 2
)

// Enum value maps for IssuerAuthType.
var (
	IssuerAuthType_name = map[int32]string{
		0: "ISSUER_AUTH_TYPE_UNSPECIFIED",
		1: "ISSUER_AUTH_TYPE_IDP",
		2: "ISSUER_AUTH_TYPE_SELF",
	}
	IssuerAuthType_value = map[string]int32{
		"ISSUER_AUTH_TYPE_UNSPECIFIED": 0,
		"ISSUER_AUTH_TYPE_IDP":         1,
		"ISSUER_AUTH_TYPE_SELF":        2,
	}
)

func (x IssuerAuthType) Enum() *IssuerAuthType {
	p := new(IssuerAuthType)
	*p = x
	return p
}

func (x IssuerAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssuerAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_agntcy_identity_core_v1alpha1_issuer_proto_enumTypes[0].Descriptor()
}

func (IssuerAuthType) Type() protoreflect.EnumType {
	return &file_agntcy_identity_core_v1alpha1_issuer_proto_enumTypes[0]
}

func (x IssuerAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssuerAuthType.Descriptor instead.
func (IssuerAuthType) EnumDescriptor() ([]byte, []int) {
	return file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescGZIP(), []int{0}
}

// A Identity Issuer
type Issuer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organization of the issuer
	Organization *string `protobuf:"bytes,1,opt,name=organization,proto3,oneof" json:"organization,omitempty"`
	// The sub organization of the issuer
	SubOrganization *string `protobuf:"bytes,2,opt,name=sub_organization,json=subOrganization,proto3,oneof" json:"sub_organization,omitempty"`
	// The common name of the issuer
	// Could be a FQDN or a FQDA
	CommonName *string `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3,oneof" json:"common_name,omitempty"`
	// This will be set to true when issuer provides a valid proof of ownership
	// of the common name on registration
	Verified *bool `protobuf:"varint,6,opt,name=verified,proto3,oneof" json:"verified,omitempty"`
	// This field is optional
	// The keys of the issuer in JWK format
	// The public key is used to verify the signature of the different claims
	PublicKey *Jwk `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	// This field is optional
	// The private key of the issuer in JWK format
	PrivateKey *Jwk `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3,oneof" json:"private_key,omitempty"`
	// This field specifies the authentication mechanism used by the issuer.
	// It determines whether the issuer uses an external Identity Provider (IDP)
	// or a self-issued key for authentication.
	AuthType      *IssuerAuthType `protobuf:"varint,7,opt,name=auth_type,json=authType,proto3,enum=agntcy.identity.core.v1alpha1.IssuerAuthType,oneof" json:"auth_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issuer) Reset() {
	*x = Issuer{}
	mi := &file_agntcy_identity_core_v1alpha1_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issuer) ProtoMessage() {}

func (x *Issuer) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_core_v1alpha1_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issuer.ProtoReflect.Descriptor instead.
func (*Issuer) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *Issuer) GetOrganization() string {
	if x != nil && x.Organization != nil {
		return *x.Organization
	}
	return ""
}

func (x *Issuer) GetSubOrganization() string {
	if x != nil && x.SubOrganization != nil {
		return *x.SubOrganization
	}
	return ""
}

func (x *Issuer) GetCommonName() string {
	if x != nil && x.CommonName != nil {
		return *x.CommonName
	}
	return ""
}

func (x *Issuer) GetVerified() bool {
	if x != nil && x.Verified != nil {
		return *x.Verified
	}
	return false
}

func (x *Issuer) GetPublicKey() *Jwk {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Issuer) GetPrivateKey() *Jwk {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Issuer) GetAuthType() IssuerAuthType {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return IssuerAuthType_ISSUER_AUTH_TYPE_UNSPECIFIED
}

var File_agntcy_identity_core_v1alpha1_issuer_proto protoreflect.FileDescriptor

const file_agntcy_identity_core_v1alpha1_issuer_proto_rawDesc = "" +
	"\n" +
	"*agntcy/identity/core/v1alpha1/issuer.proto\x12\x1dagntcy.identity.core.v1alpha1\x1a&agntcy/identity/core/v1alpha1/id.proto\"\xfb\x03\n" +
	"\x06Issuer\x12'\n" +
	"\forganization\x18\x01 \x01(\tH\x00R\forganization\x88\x01\x01\x12.\n" +
	"\x10sub_organization\x18\x02 \x01(\tH\x01R\x0fsubOrganization\x88\x01\x01\x12$\n" +
	"\vcommon_name\x18\x03 \x01(\tH\x02R\n" +
	"commonName\x88\x01\x01\x12\x1f\n" +
	"\bverified\x18\x06 \x01(\bH\x03R\bverified\x88\x01\x01\x12F\n" +
	"\n" +
	"public_key\x18\x04 \x01(\v2\".agntcy.identity.core.v1alpha1.JwkH\x04R\tpublicKey\x88\x01\x01\x12H\n" +
	"\vprivate_key\x18\x05 \x01(\v2\".agntcy.identity.core.v1alpha1.JwkH\x05R\n" +
	"privateKey\x88\x01\x01\x12O\n" +
	"\tauth_type\x18\a \x01(\x0e2-.agntcy.identity.core.v1alpha1.IssuerAuthTypeH\x06R\bauthType\x88\x01\x01B\x0f\n" +
	"\r_organizationB\x13\n" +
	"\x11_sub_organizationB\x0e\n" +
	"\f_common_nameB\v\n" +
	"\t_verifiedB\r\n" +
	"\v_public_keyB\x0e\n" +
	"\f_private_keyB\f\n" +
	"\n" +
	"_auth_type*g\n" +
	"\x0eIssuerAuthType\x12 \n" +
	"\x1cISSUER_AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ISSUER_AUTH_TYPE_IDP\x10\x01\x12\x19\n" +
	"\x15ISSUER_AUTH_TYPE_SELF\x10\x02BZZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_gob\x06proto3"

var (
	file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescOnce sync.Once
	file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescData []byte
)

func file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescGZIP() []byte {
	file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_issuer_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_issuer_proto_rawDesc)))
	})
	return file_agntcy_identity_core_v1alpha1_issuer_proto_rawDescData
}

var file_agntcy_identity_core_v1alpha1_issuer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agntcy_identity_core_v1alpha1_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agntcy_identity_core_v1alpha1_issuer_proto_goTypes = []any{
	(IssuerAuthType)(0), // 0: agntcy.identity.core.v1alpha1.IssuerAuthType
	(*Issuer)(nil),      // 1: agntcy.identity.core.v1alpha1.Issuer
	(*Jwk)(nil),         // 2: agntcy.identity.core.v1alpha1.Jwk
}
var file_agntcy_identity_core_v1alpha1_issuer_proto_depIdxs = []int32{
	2, // 0: agntcy.identity.core.v1alpha1.Issuer.public_key:type_name -> agntcy.identity.core.v1alpha1.Jwk
	2, // 1: agntcy.identity.core.v1alpha1.Issuer.private_key:type_name -> agntcy.identity.core.v1alpha1.Jwk
	0, // 2: agntcy.identity.core.v1alpha1.Issuer.auth_type:type_name -> agntcy.identity.core.v1alpha1.IssuerAuthType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agntcy_identity_core_v1alpha1_issuer_proto_init() }
func file_agntcy_identity_core_v1alpha1_issuer_proto_init() {
	if File_agntcy_identity_core_v1alpha1_issuer_proto != nil {
		return
	}
	file_agntcy_identity_core_v1alpha1_id_proto_init()
	file_agntcy_identity_core_v1alpha1_issuer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_issuer_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_issuer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_identity_core_v1alpha1_issuer_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_core_v1alpha1_issuer_proto_depIdxs,
		EnumInfos:         file_agntcy_identity_core_v1alpha1_issuer_proto_enumTypes,
		MessageInfos:      file_agntcy_identity_core_v1alpha1_issuer_proto_msgTypes,
	}.Build()
	File_agntcy_identity_core_v1alpha1_issuer_proto = out.File
	file_agntcy_identity_core_v1alpha1_issuer_proto_goTypes = nil
	file_agntcy_identity_core_v1alpha1_issuer_proto_depIdxs = nil
}
