// This file was autogenerated by go-to-protobuf. Do not edit it manually!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/core/v1alpha1/jwk.proto

package identity_core_sdk_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JWK represents:
// - a JSON Web Key (JWK) with the respective fields specific to RSA algorithms.
// - a Quantum JSON Web Key (QJWK) with the respective fields specific to AKP algorithms.
type Jwk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ALG represents the algorithm intended for use with the key.
	// Example algorithms for Post-Quantum ML-DSA family:
	// "ML-DSA-44", "ML-DSA-65", "ML-DSA-87".
	// Some example algorithms are "RS256", "RS384", "RS512" for RSA algorithms.
	Alg *string `protobuf:"bytes,1,opt,name=alg,proto3,oneof" json:"alg,omitempty"`
	// KTY represents the key type parameter.
	// It specifies the family of quantum algorithms used with the key,
	// such as "AKP" for post quantum algorithms
	// or "RSA" for non quantum algorithms.
	Kty *string `protobuf:"bytes,2,opt,name=kty,proto3,oneof" json:"kty,omitempty"`
	// Use represents the intended use of the key.
	// Some example values are "enc" and "sig".
	Use *string `protobuf:"bytes,3,opt,name=use,proto3,oneof" json:"use,omitempty"`
	// KID represents the key ID.
	// It is used to match a specific key.
	Kid *string `protobuf:"bytes,4,opt,name=kid,proto3,oneof" json:"kid,omitempty"`
	// The public key for the AKP kty.
	Pub *string `protobuf:"bytes,5,opt,name=pub,proto3,oneof" json:"pub,omitempty"`
	// The private key for the AKP kty.
	Priv *string `protobuf:"bytes,6,opt,name=priv,proto3,oneof" json:"priv,omitempty"`
	// Seed used to derive keys for ML-DSA alg.
	Seed *string `protobuf:"bytes,7,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	// The exponent for the RSA public key.
	E *string `protobuf:"bytes,8,opt,name=e,proto3,oneof" json:"e,omitempty"`
	// The modulus for the RSA public key.
	N *string `protobuf:"bytes,9,opt,name=n,proto3,oneof" json:"n,omitempty"`
	// The private exponent for the RSA kty.
	D *string `protobuf:"bytes,10,opt,name=d,proto3,oneof" json:"d,omitempty"`
	// The first prime factor for the RSA private key.
	P *string `protobuf:"bytes,11,opt,name=p,proto3,oneof" json:"p,omitempty"`
	// The second prime factor for the RSA private key.
	Q *string `protobuf:"bytes,12,opt,name=q,proto3,oneof" json:"q,omitempty"`
	// The first factor CRT exponent for the RSA private key.
	Dp *string `protobuf:"bytes,13,opt,name=dp,proto3,oneof" json:"dp,omitempty"`
	// The second factor CRT exponent for the RSA private key.
	Dq *string `protobuf:"bytes,14,opt,name=dq,proto3,oneof" json:"dq,omitempty"`
	// The first CRT coefficient for the RSA private key.
	Qi            *string `protobuf:"bytes,15,opt,name=qi,proto3,oneof" json:"qi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *Jwk) GetAlg() string {
	if x != nil && x.Alg != nil {
		return *x.Alg
	}
	return ""
}

func (x *Jwk) GetKty() string {
	if x != nil && x.Kty != nil {
		return *x.Kty
	}
	return ""
}

func (x *Jwk) GetUse() string {
	if x != nil && x.Use != nil {
		return *x.Use
	}
	return ""
}

func (x *Jwk) GetKid() string {
	if x != nil && x.Kid != nil {
		return *x.Kid
	}
	return ""
}

func (x *Jwk) GetPub() string {
	if x != nil && x.Pub != nil {
		return *x.Pub
	}
	return ""
}

func (x *Jwk) GetPriv() string {
	if x != nil && x.Priv != nil {
		return *x.Priv
	}
	return ""
}

func (x *Jwk) GetSeed() string {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return ""
}

func (x *Jwk) GetE() string {
	if x != nil && x.E != nil {
		return *x.E
	}
	return ""
}

func (x *Jwk) GetN() string {
	if x != nil && x.N != nil {
		return *x.N
	}
	return ""
}

func (x *Jwk) GetD() string {
	if x != nil && x.D != nil {
		return *x.D
	}
	return ""
}

func (x *Jwk) GetP() string {
	if x != nil && x.P != nil {
		return *x.P
	}
	return ""
}

func (x *Jwk) GetQ() string {
	if x != nil && x.Q != nil {
		return *x.Q
	}
	return ""
}

func (x *Jwk) GetDp() string {
	if x != nil && x.Dp != nil {
		return *x.Dp
	}
	return ""
}

func (x *Jwk) GetDq() string {
	if x != nil && x.Dq != nil {
		return *x.Dq
	}
	return ""
}

func (x *Jwk) GetQi() string {
	if x != nil && x.Qi != nil {
		return *x.Qi
	}
	return ""
}

// JWKS represents a set of JSON Web Keys (JWKs).
type Jwks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keys represents the list of JSON Web Keys.
	Keys          []*Jwk `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwks) Reset() {
	*x = Jwks{}
	mi := &file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwks) ProtoMessage() {}

func (x *Jwks) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwks.ProtoReflect.Descriptor instead.
func (*Jwks) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescGZIP(), []int{1}
}

func (x *Jwks) GetKeys() []*Jwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_agntcy_identity_core_v1alpha1_jwk_proto protoreflect.FileDescriptor

const file_agntcy_identity_core_v1alpha1_jwk_proto_rawDesc = "" +
	"\n" +
	"'agntcy/identity/core/v1alpha1/jwk.proto\x12\x1dagntcy.identity.core.v1alpha1\"\xb5\x03\n" +
	"\x03Jwk\x12\x15\n" +
	"\x03alg\x18\x01 \x01(\tH\x00R\x03alg\x88\x01\x01\x12\x15\n" +
	"\x03kty\x18\x02 \x01(\tH\x01R\x03kty\x88\x01\x01\x12\x15\n" +
	"\x03use\x18\x03 \x01(\tH\x02R\x03use\x88\x01\x01\x12\x15\n" +
	"\x03kid\x18\x04 \x01(\tH\x03R\x03kid\x88\x01\x01\x12\x15\n" +
	"\x03pub\x18\x05 \x01(\tH\x04R\x03pub\x88\x01\x01\x12\x17\n" +
	"\x04priv\x18\x06 \x01(\tH\x05R\x04priv\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\a \x01(\tH\x06R\x04seed\x88\x01\x01\x12\x11\n" +
	"\x01e\x18\b \x01(\tH\aR\x01e\x88\x01\x01\x12\x11\n" +
	"\x01n\x18\t \x01(\tH\bR\x01n\x88\x01\x01\x12\x11\n" +
	"\x01d\x18\n" +
	" \x01(\tH\tR\x01d\x88\x01\x01\x12\x11\n" +
	"\x01p\x18\v \x01(\tH\n" +
	"R\x01p\x88\x01\x01\x12\x11\n" +
	"\x01q\x18\f \x01(\tH\vR\x01q\x88\x01\x01\x12\x13\n" +
	"\x02dp\x18\r \x01(\tH\fR\x02dp\x88\x01\x01\x12\x13\n" +
	"\x02dq\x18\x0e \x01(\tH\rR\x02dq\x88\x01\x01\x12\x13\n" +
	"\x02qi\x18\x0f \x01(\tH\x0eR\x02qi\x88\x01\x01B\x06\n" +
	"\x04_algB\x06\n" +
	"\x04_ktyB\x06\n" +
	"\x04_useB\x06\n" +
	"\x04_kidB\x06\n" +
	"\x04_pubB\a\n" +
	"\x05_privB\a\n" +
	"\x05_seedB\x04\n" +
	"\x02_eB\x04\n" +
	"\x02_nB\x04\n" +
	"\x02_dB\x04\n" +
	"\x02_pB\x04\n" +
	"\x02_qB\x05\n" +
	"\x03_dpB\x05\n" +
	"\x03_dqB\x05\n" +
	"\x03_qi\">\n" +
	"\x04Jwks\x126\n" +
	"\x04keys\x18\x01 \x03(\v2\".agntcy.identity.core.v1alpha1.JwkR\x04keysBZZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_gob\x06proto3"

var (
	file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescOnce sync.Once
	file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescData []byte
)

func file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescGZIP() []byte {
	file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_jwk_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_jwk_proto_rawDesc)))
	})
	return file_agntcy_identity_core_v1alpha1_jwk_proto_rawDescData
}

var file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agntcy_identity_core_v1alpha1_jwk_proto_goTypes = []any{
	(*Jwk)(nil),  // 0: agntcy.identity.core.v1alpha1.Jwk
	(*Jwks)(nil), // 1: agntcy.identity.core.v1alpha1.Jwks
}
var file_agntcy_identity_core_v1alpha1_jwk_proto_depIdxs = []int32{
	0, // 0: agntcy.identity.core.v1alpha1.Jwks.keys:type_name -> agntcy.identity.core.v1alpha1.Jwk
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agntcy_identity_core_v1alpha1_jwk_proto_init() }
func file_agntcy_identity_core_v1alpha1_jwk_proto_init() {
	if File_agntcy_identity_core_v1alpha1_jwk_proto != nil {
		return
	}
	file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_core_v1alpha1_jwk_proto_rawDesc), len(file_agntcy_identity_core_v1alpha1_jwk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_identity_core_v1alpha1_jwk_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_core_v1alpha1_jwk_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_core_v1alpha1_jwk_proto_msgTypes,
	}.Build()
	File_agntcy_identity_core_v1alpha1_jwk_proto = out.File
	file_agntcy_identity_core_v1alpha1_jwk_proto_goTypes = nil
	file_agntcy_identity_core_v1alpha1_jwk_proto_depIdxs = nil
}
