FROM golang:1.22.5-alpine AS builder

RUN apk update && apk add python3 python3-dev py3-pip gcc g++
RUN go env -w CGO_CFLAGS="-I/usr/include/python3.12"
RUN go env -w CGO_LDFLAGS="-I/usr/lib/python3.12 -lpython3.12"

WORKDIR /src
COPY ./backend .
RUN go mod download
