// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// NewPublishVerifiableCredentialParams creates a new PublishVerifiableCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublishVerifiableCredentialParams() *PublishVerifiableCredentialParams {
	return &PublishVerifiableCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublishVerifiableCredentialParamsWithTimeout creates a new PublishVerifiableCredentialParams object
// with the ability to set a timeout on a request.
func NewPublishVerifiableCredentialParamsWithTimeout(timeout time.Duration) *PublishVerifiableCredentialParams {
	return &PublishVerifiableCredentialParams{
		timeout: timeout,
	}
}

// NewPublishVerifiableCredentialParamsWithContext creates a new PublishVerifiableCredentialParams object
// with the ability to set a context for a request.
func NewPublishVerifiableCredentialParamsWithContext(ctx context.Context) *PublishVerifiableCredentialParams {
	return &PublishVerifiableCredentialParams{
		Context: ctx,
	}
}

// NewPublishVerifiableCredentialParamsWithHTTPClient creates a new PublishVerifiableCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublishVerifiableCredentialParamsWithHTTPClient(client *http.Client) *PublishVerifiableCredentialParams {
	return &PublishVerifiableCredentialParams{
		HTTPClient: client,
	}
}

/*
PublishVerifiableCredentialParams contains all the parameters to send to the API endpoint

	for the publish verifiable credential operation.

	Typically these are written to a http.Request.
*/
type PublishVerifiableCredentialParams struct {

	// Body.
	Body *models.V1alpha1PublishRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the publish verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishVerifiableCredentialParams) WithDefaults() *PublishVerifiableCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the publish verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishVerifiableCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) WithTimeout(timeout time.Duration) *PublishVerifiableCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) WithContext(ctx context.Context) *PublishVerifiableCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) WithHTTPClient(client *http.Client) *PublishVerifiableCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) WithBody(body *models.V1alpha1PublishRequest) *PublishVerifiableCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the publish verifiable credential params
func (o *PublishVerifiableCredentialParams) SetBody(body *models.V1alpha1PublishRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublishVerifiableCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
