// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// NewRevokeVerifiableCredentialParams creates a new RevokeVerifiableCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRevokeVerifiableCredentialParams() *RevokeVerifiableCredentialParams {
	return &RevokeVerifiableCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRevokeVerifiableCredentialParamsWithTimeout creates a new RevokeVerifiableCredentialParams object
// with the ability to set a timeout on a request.
func NewRevokeVerifiableCredentialParamsWithTimeout(timeout time.Duration) *RevokeVerifiableCredentialParams {
	return &RevokeVerifiableCredentialParams{
		timeout: timeout,
	}
}

// NewRevokeVerifiableCredentialParamsWithContext creates a new RevokeVerifiableCredentialParams object
// with the ability to set a context for a request.
func NewRevokeVerifiableCredentialParamsWithContext(ctx context.Context) *RevokeVerifiableCredentialParams {
	return &RevokeVerifiableCredentialParams{
		Context: ctx,
	}
}

// NewRevokeVerifiableCredentialParamsWithHTTPClient creates a new RevokeVerifiableCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewRevokeVerifiableCredentialParamsWithHTTPClient(client *http.Client) *RevokeVerifiableCredentialParams {
	return &RevokeVerifiableCredentialParams{
		HTTPClient: client,
	}
}

/*
RevokeVerifiableCredentialParams contains all the parameters to send to the API endpoint

	for the revoke verifiable credential operation.

	Typically these are written to a http.Request.
*/
type RevokeVerifiableCredentialParams struct {

	// Body.
	Body *models.V1alpha1RevokeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the revoke verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevokeVerifiableCredentialParams) WithDefaults() *RevokeVerifiableCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the revoke verifiable credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevokeVerifiableCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) WithTimeout(timeout time.Duration) *RevokeVerifiableCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) WithContext(ctx context.Context) *RevokeVerifiableCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) WithHTTPClient(client *http.Client) *RevokeVerifiableCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) WithBody(body *models.V1alpha1RevokeRequest) *RevokeVerifiableCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the revoke verifiable credential params
func (o *RevokeVerifiableCredentialParams) SetBody(body *models.V1alpha1RevokeRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RevokeVerifiableCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
