// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// RevokeVerifiableCredentialReader is a Reader for the RevokeVerifiableCredential structure.
type RevokeVerifiableCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeVerifiableCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeVerifiableCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRevokeVerifiableCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRevokeVerifiableCredentialOK creates a RevokeVerifiableCredentialOK with default headers values
func NewRevokeVerifiableCredentialOK() *RevokeVerifiableCredentialOK {
	return &RevokeVerifiableCredentialOK{}
}

/*
RevokeVerifiableCredentialOK describes a response with status code 200, with default header values.

A successful response.
*/
type RevokeVerifiableCredentialOK struct {
	Payload any
}

// IsSuccess returns true when this revoke verifiable credential o k response has a 2xx status code
func (o *RevokeVerifiableCredentialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revoke verifiable credential o k response has a 3xx status code
func (o *RevokeVerifiableCredentialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke verifiable credential o k response has a 4xx status code
func (o *RevokeVerifiableCredentialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke verifiable credential o k response has a 5xx status code
func (o *RevokeVerifiableCredentialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke verifiable credential o k response a status code equal to that given
func (o *RevokeVerifiableCredentialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revoke verifiable credential o k response
func (o *RevokeVerifiableCredentialOK) Code() int {
	return 200
}

func (o *RevokeVerifiableCredentialOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/revoke][%d] revokeVerifiableCredentialOK %s", 200, payload)
}

func (o *RevokeVerifiableCredentialOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/revoke][%d] revokeVerifiableCredentialOK %s", 200, payload)
}

func (o *RevokeVerifiableCredentialOK) GetPayload() any {
	return o.Payload
}

func (o *RevokeVerifiableCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRevokeVerifiableCredentialDefault creates a RevokeVerifiableCredentialDefault with default headers values
func NewRevokeVerifiableCredentialDefault(code int) *RevokeVerifiableCredentialDefault {
	return &RevokeVerifiableCredentialDefault{
		_statusCode: code,
	}
}

/*
RevokeVerifiableCredentialDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RevokeVerifiableCredentialDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this revoke verifiable credential default response has a 2xx status code
func (o *RevokeVerifiableCredentialDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this revoke verifiable credential default response has a 3xx status code
func (o *RevokeVerifiableCredentialDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this revoke verifiable credential default response has a 4xx status code
func (o *RevokeVerifiableCredentialDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this revoke verifiable credential default response has a 5xx status code
func (o *RevokeVerifiableCredentialDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this revoke verifiable credential default response a status code equal to that given
func (o *RevokeVerifiableCredentialDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the revoke verifiable credential default response
func (o *RevokeVerifiableCredentialDefault) Code() int {
	return o._statusCode
}

func (o *RevokeVerifiableCredentialDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/revoke][%d] RevokeVerifiableCredential default %s", o._statusCode, payload)
}

func (o *RevokeVerifiableCredentialDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/revoke][%d] RevokeVerifiableCredential default %s", o._statusCode, payload)
}

func (o *RevokeVerifiableCredentialDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RevokeVerifiableCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
