// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// SearchVerifiableCredentialsReader is a Reader for the SearchVerifiableCredentials structure.
type SearchVerifiableCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchVerifiableCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchVerifiableCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchVerifiableCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchVerifiableCredentialsOK creates a SearchVerifiableCredentialsOK with default headers values
func NewSearchVerifiableCredentialsOK() *SearchVerifiableCredentialsOK {
	return &SearchVerifiableCredentialsOK{}
}

/*
SearchVerifiableCredentialsOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchVerifiableCredentialsOK struct {
	Payload *models.V1alpha1SearchResponse
}

// IsSuccess returns true when this search verifiable credentials o k response has a 2xx status code
func (o *SearchVerifiableCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search verifiable credentials o k response has a 3xx status code
func (o *SearchVerifiableCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search verifiable credentials o k response has a 4xx status code
func (o *SearchVerifiableCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search verifiable credentials o k response has a 5xx status code
func (o *SearchVerifiableCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search verifiable credentials o k response a status code equal to that given
func (o *SearchVerifiableCredentialsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search verifiable credentials o k response
func (o *SearchVerifiableCredentialsOK) Code() int {
	return 200
}

func (o *SearchVerifiableCredentialsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/search][%d] searchVerifiableCredentialsOK %s", 200, payload)
}

func (o *SearchVerifiableCredentialsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/search][%d] searchVerifiableCredentialsOK %s", 200, payload)
}

func (o *SearchVerifiableCredentialsOK) GetPayload() *models.V1alpha1SearchResponse {
	return o.Payload
}

func (o *SearchVerifiableCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1SearchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchVerifiableCredentialsDefault creates a SearchVerifiableCredentialsDefault with default headers values
func NewSearchVerifiableCredentialsDefault(code int) *SearchVerifiableCredentialsDefault {
	return &SearchVerifiableCredentialsDefault{
		_statusCode: code,
	}
}

/*
SearchVerifiableCredentialsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SearchVerifiableCredentialsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this search verifiable credentials default response has a 2xx status code
func (o *SearchVerifiableCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search verifiable credentials default response has a 3xx status code
func (o *SearchVerifiableCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search verifiable credentials default response has a 4xx status code
func (o *SearchVerifiableCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search verifiable credentials default response has a 5xx status code
func (o *SearchVerifiableCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search verifiable credentials default response a status code equal to that given
func (o *SearchVerifiableCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the search verifiable credentials default response
func (o *SearchVerifiableCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *SearchVerifiableCredentialsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/search][%d] SearchVerifiableCredentials default %s", o._statusCode, payload)
}

func (o *SearchVerifiableCredentialsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/search][%d] SearchVerifiableCredentials default %s", o._statusCode, payload)
}

func (o *SearchVerifiableCredentialsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SearchVerifiableCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
