// Code generated by go-swagger; DO NOT EDIT.

package vc_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// VerifyVerifiableCredentialReader is a Reader for the VerifyVerifiableCredential structure.
type VerifyVerifiableCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyVerifiableCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyVerifiableCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyVerifiableCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyVerifiableCredentialOK creates a VerifyVerifiableCredentialOK with default headers values
func NewVerifyVerifiableCredentialOK() *VerifyVerifiableCredentialOK {
	return &VerifyVerifiableCredentialOK{}
}

/*
VerifyVerifiableCredentialOK describes a response with status code 200, with default header values.

A successful response.
*/
type VerifyVerifiableCredentialOK struct {
	Payload interface{}
}

// IsSuccess returns true when this verify verifiable credential o k response has a 2xx status code
func (o *VerifyVerifiableCredentialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this verify verifiable credential o k response has a 3xx status code
func (o *VerifyVerifiableCredentialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify verifiable credential o k response has a 4xx status code
func (o *VerifyVerifiableCredentialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this verify verifiable credential o k response has a 5xx status code
func (o *VerifyVerifiableCredentialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this verify verifiable credential o k response a status code equal to that given
func (o *VerifyVerifiableCredentialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the verify verifiable credential o k response
func (o *VerifyVerifiableCredentialOK) Code() int {
	return 200
}

func (o *VerifyVerifiableCredentialOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/verify][%d] verifyVerifiableCredentialOK %s", 200, payload)
}

func (o *VerifyVerifiableCredentialOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/verify][%d] verifyVerifiableCredentialOK %s", 200, payload)
}

func (o *VerifyVerifiableCredentialOK) GetPayload() interface{} {
	return o.Payload
}

func (o *VerifyVerifiableCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVerifyVerifiableCredentialDefault creates a VerifyVerifiableCredentialDefault with default headers values
func NewVerifyVerifiableCredentialDefault(code int) *VerifyVerifiableCredentialDefault {
	return &VerifyVerifiableCredentialDefault{
		_statusCode: code,
	}
}

/*
VerifyVerifiableCredentialDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type VerifyVerifiableCredentialDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this verify verifiable credential default response has a 2xx status code
func (o *VerifyVerifiableCredentialDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this verify verifiable credential default response has a 3xx status code
func (o *VerifyVerifiableCredentialDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this verify verifiable credential default response has a 4xx status code
func (o *VerifyVerifiableCredentialDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this verify verifiable credential default response has a 5xx status code
func (o *VerifyVerifiableCredentialDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this verify verifiable credential default response a status code equal to that given
func (o *VerifyVerifiableCredentialDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the verify verifiable credential default response
func (o *VerifyVerifiableCredentialDefault) Code() int {
	return o._statusCode
}

func (o *VerifyVerifiableCredentialDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/verify][%d] VerifyVerifiableCredential default %s", o._statusCode, payload)
}

func (o *VerifyVerifiableCredentialDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/vc/verify][%d] VerifyVerifiableCredential default %s", o._statusCode, payload)
}

func (o *VerifyVerifiableCredentialDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *VerifyVerifiableCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
