# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
# Default state for all rules
default: true
# Path to configuration file to extend
extends: null

# MD013/line-length
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 300
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD024/no-duplicate-heading
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md024.md
MD024:
  # Only check sibling headings
  siblings_only: true

# MD025/single-title/single-h1
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md025.md
MD025:
  # RegExp for matching title in front matter
  front_matter_title: ""

# MD041/first-line-heading/first-line-h1
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md041.md
MD041:
  # RegExp for matching title in front matter
  front_matter_title: ""

# MD033/no-inline-html
MD033:
  allowed_elements: ['a', 'img', 'alt', 'p', 'br', 'b', 'caption', 'picture', 'source']
