// Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/issuer/v1alpha1/local_service.proto

package identity_issuer_sdk_go

import (
	v1alpha1 "github.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Issues a Verifiable Credential in a specific Envelope Type
type IssueVCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Content of the VC
	Content *v1alpha1.CredentialContent `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Envelope type
	EnvelopeType  v1alpha1.CredentialEnvelopeType `protobuf:"varint,3,opt,name=envelope_type,json=envelopeType,proto3,enum=agntcy.identity.core.v1alpha1.CredentialEnvelopeType" json:"envelope_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueVCRequest) Reset() {
	*x = IssueVCRequest{}
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVCRequest) ProtoMessage() {}

func (x *IssueVCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVCRequest.ProtoReflect.Descriptor instead.
func (*IssueVCRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescGZIP(), []int{0}
}

func (x *IssueVCRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueVCRequest) GetContent() *v1alpha1.CredentialContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IssueVCRequest) GetEnvelopeType() v1alpha1.CredentialEnvelopeType {
	if x != nil {
		return x.EnvelopeType
	}
	return v1alpha1.CredentialEnvelopeType(0)
}

// Returns the Verifiable Credential in the requested Envelope Type
type IssueVCResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The issued VC
	Vc            *v1alpha1.EnvelopedCredential `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueVCResponse) Reset() {
	*x = IssueVCResponse{}
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVCResponse) ProtoMessage() {}

func (x *IssueVCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVCResponse.ProtoReflect.Descriptor instead.
func (*IssueVCResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescGZIP(), []int{1}
}

func (x *IssueVCResponse) GetVc() *v1alpha1.EnvelopedCredential {
	if x != nil {
		return x.Vc
	}
	return nil
}

// Returns the generated keypair in Json Web Key (JWK) format
type KeyGenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generated keypair
	Keypair       *v1alpha1.Jwk `protobuf:"bytes,1,opt,name=keypair,proto3" json:"keypair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGenResponse) Reset() {
	*x = KeyGenResponse{}
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenResponse) ProtoMessage() {}

func (x *KeyGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenResponse.ProtoReflect.Descriptor instead.
func (*KeyGenResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescGZIP(), []int{2}
}

func (x *KeyGenResponse) GetKeypair() *v1alpha1.Jwk {
	if x != nil {
		return x.Keypair
	}
	return nil
}

var File_agntcy_identity_issuer_v1alpha1_local_service_proto protoreflect.FileDescriptor

const file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDesc = "" +
	"\n" +
	"3agntcy/identity/issuer/v1alpha1/local_service.proto\x12\x1fagntcy.identity.issuer.v1alpha1\x1a&agntcy/identity/core/v1alpha1/id.proto\x1a&agntcy/identity/core/v1alpha1/vc.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc8\x01\n" +
	"\x0eIssueVCRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12J\n" +
	"\acontent\x18\x02 \x01(\v20.agntcy.identity.core.v1alpha1.CredentialContentR\acontent\x12Z\n" +
	"\renvelope_type\x18\x03 \x01(\x0e25.agntcy.identity.core.v1alpha1.CredentialEnvelopeTypeR\fenvelopeType\"U\n" +
	"\x0fIssueVCResponse\x12B\n" +
	"\x02vc\x18\x01 \x01(\v22.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x02vc\"N\n" +
	"\x0eKeyGenResponse\x12<\n" +
	"\akeypair\x18\x01 \x01(\v2\".agntcy.identity.core.v1alpha1.JwkR\akeypair2\xcf\x01\n" +
	"\fLocalService\x12Q\n" +
	"\x06KeyGen\x12\x16.google.protobuf.Empty\x1a/.agntcy.identity.issuer.v1alpha1.KeyGenResponse\x12l\n" +
	"\aIssueVC\x12/.agntcy.identity.issuer.v1alpha1.IssueVCRequest\x1a0.agntcy.identity.issuer.v1alpha1.IssueVCResponseB^Z\\github.com/agntcy/identity/api/server/agntcy/identity/issuer/v1alpha1;identity_issuer_sdk_gob\x06proto3"

var (
	file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescOnce sync.Once
	file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescData []byte
)

func file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescGZIP() []byte {
	file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDesc), len(file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDesc)))
	})
	return file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDescData
}

var file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agntcy_identity_issuer_v1alpha1_local_service_proto_goTypes = []any{
	(*IssueVCRequest)(nil),               // 0: agntcy.identity.issuer.v1alpha1.IssueVCRequest
	(*IssueVCResponse)(nil),              // 1: agntcy.identity.issuer.v1alpha1.IssueVCResponse
	(*KeyGenResponse)(nil),               // 2: agntcy.identity.issuer.v1alpha1.KeyGenResponse
	(*v1alpha1.CredentialContent)(nil),   // 3: agntcy.identity.core.v1alpha1.CredentialContent
	(v1alpha1.CredentialEnvelopeType)(0), // 4: agntcy.identity.core.v1alpha1.CredentialEnvelopeType
	(*v1alpha1.EnvelopedCredential)(nil), // 5: agntcy.identity.core.v1alpha1.EnvelopedCredential
	(*v1alpha1.Jwk)(nil),                 // 6: agntcy.identity.core.v1alpha1.Jwk
	(*emptypb.Empty)(nil),                // 7: google.protobuf.Empty
}
var file_agntcy_identity_issuer_v1alpha1_local_service_proto_depIdxs = []int32{
	3, // 0: agntcy.identity.issuer.v1alpha1.IssueVCRequest.content:type_name -> agntcy.identity.core.v1alpha1.CredentialContent
	4, // 1: agntcy.identity.issuer.v1alpha1.IssueVCRequest.envelope_type:type_name -> agntcy.identity.core.v1alpha1.CredentialEnvelopeType
	5, // 2: agntcy.identity.issuer.v1alpha1.IssueVCResponse.vc:type_name -> agntcy.identity.core.v1alpha1.EnvelopedCredential
	6, // 3: agntcy.identity.issuer.v1alpha1.KeyGenResponse.keypair:type_name -> agntcy.identity.core.v1alpha1.Jwk
	7, // 4: agntcy.identity.issuer.v1alpha1.LocalService.KeyGen:input_type -> google.protobuf.Empty
	0, // 5: agntcy.identity.issuer.v1alpha1.LocalService.IssueVC:input_type -> agntcy.identity.issuer.v1alpha1.IssueVCRequest
	2, // 6: agntcy.identity.issuer.v1alpha1.LocalService.KeyGen:output_type -> agntcy.identity.issuer.v1alpha1.KeyGenResponse
	1, // 7: agntcy.identity.issuer.v1alpha1.LocalService.IssueVC:output_type -> agntcy.identity.issuer.v1alpha1.IssueVCResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agntcy_identity_issuer_v1alpha1_local_service_proto_init() }
func file_agntcy_identity_issuer_v1alpha1_local_service_proto_init() {
	if File_agntcy_identity_issuer_v1alpha1_local_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDesc), len(file_agntcy_identity_issuer_v1alpha1_local_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agntcy_identity_issuer_v1alpha1_local_service_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_issuer_v1alpha1_local_service_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_issuer_v1alpha1_local_service_proto_msgTypes,
	}.Build()
	File_agntcy_identity_issuer_v1alpha1_local_service_proto = out.File
	file_agntcy_identity_issuer_v1alpha1_local_service_proto_goTypes = nil
	file_agntcy_identity_issuer_v1alpha1_local_service_proto_depIdxs = nil
}
