# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/core/v1alpha1/errors.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*agntcy/identity/core/v1alpha1/errors.proto\x12\x1d\x61gntcy.identity.core.v1alpha1\"\x8a\x01\n\tErrorInfo\x12G\n\x06reason\x18\x01 \x01(\x0e\x32*.agntcy.identity.core.v1alpha1.ErrorReasonH\x00R\x06reason\x88\x01\x01\x12\x1d\n\x07message\x18\x02 \x01(\tH\x01R\x07message\x88\x01\x01\x42\t\n\x07_reasonB\n\n\x08_message*\xb4\x04\n\x0b\x45rrorReason\x12\x1c\n\x18\x45RROR_REASON_UNSPECIFIED\x10\x00\x12\x19\n\x15\x45RROR_REASON_INTERNAL\x10\x01\x12\x31\n-ERROR_REASON_INVALID_CREDENTIAL_ENVELOPE_TYPE\x10\x02\x12\x39\n5ERROR_REASON_INVALID_CREDENTIAL_ENVELOPE_VALUE_FORMAT\x10\x03\x12\x1f\n\x1b\x45RROR_REASON_INVALID_ISSUER\x10\x04\x12&\n\"ERROR_REASON_ISSUER_NOT_REGISTERED\x10\x05\x12.\n*ERROR_REASON_INVALID_VERIFIABLE_CREDENTIAL\x10\x06\x12\x1d\n\x19\x45RROR_REASON_IDP_REQUIRED\x10\x07\x12\x1e\n\x1a\x45RROR_REASON_INVALID_PROOF\x10\x08\x12\"\n\x1e\x45RROR_REASON_UNSUPPORTED_PROOF\x10\t\x12,\n(ERROR_REASON_RESOLVER_METADATA_NOT_FOUND\x10\n\x12\x1c\n\x18\x45RROR_REASON_UNKNOWN_IDP\x10\x0b\x12&\n\"ERROR_REASON_ID_ALREADY_REGISTERED\x10\x0c\x12.\n*ERROR_REASON_VERIFIABLE_CREDENTIAL_REVOKED\x10\rB\xa1\x02\n!com.agntcy.identity.core.v1alpha1B\x0b\x45rrorsProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\xa2\x02\x03\x41IC\xaa\x02\x1d\x41gntcy.Identity.Core.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Core\\V1alpha1\xe2\x02)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Core::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.core.v1alpha1.errors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.core.v1alpha1B\013ErrorsProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\242\002\003AIC\252\002\035Agntcy.Identity.Core.V1alpha1\312\002\035Agntcy\\Identity\\Core\\V1alpha1\342\002)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Core::V1alpha1'
  _globals['_ERRORREASON']._serialized_start=219
  _globals['_ERRORREASON']._serialized_end=783
  _globals['_ERRORINFO']._serialized_start=78
  _globals['_ERRORINFO']._serialized_end=216
# @@protoc_insertion_point(module_scope)
