# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/core/v1alpha1/id.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agntcy.identity.core.v1alpha1 import jwk_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_jwk__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&agntcy/identity/core/v1alpha1/id.proto\x12\x1d\x61gntcy.identity.core.v1alpha1\x1a\'agntcy/identity/core/v1alpha1/jwk.proto\"\xb3\x02\n\x10ResolverMetadata\x12\x13\n\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x62\n\x13verification_method\x18\x02 \x03(\x0b\x32\x31.agntcy.identity.core.v1alpha1.VerificationMethodR\x12verificationMethod\x12@\n\x07service\x18\x03 \x03(\x0b\x32&.agntcy.identity.core.v1alpha1.ServiceR\x07service\x12)\n\x10\x61ssertion_method\x18\x04 \x03(\tR\x0f\x61ssertionMethod\x12#\n\ncontroller\x18\x05 \x01(\tH\x01R\ncontroller\x88\x01\x01\x42\x05\n\x03_idB\r\n\x0b_controller\"4\n\x07Service\x12)\n\x10service_endpoint\x18\x01 \x03(\tR\x0fserviceEndpoint\"\x92\x01\n\x12VerificationMethod\x12\x13\n\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12M\n\x0epublic_key_jwk\x18\x02 \x01(\x0b\x32\".agntcy.identity.core.v1alpha1.JwkH\x01R\x0cpublicKeyJwk\x88\x01\x01\x42\x05\n\x03_idB\x11\n\x0f_public_key_jwkB\x9d\x02\n!com.agntcy.identity.core.v1alpha1B\x07IdProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\xa2\x02\x03\x41IC\xaa\x02\x1d\x41gntcy.Identity.Core.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Core\\V1alpha1\xe2\x02)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Core::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.core.v1alpha1.id_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.core.v1alpha1B\007IdProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\242\002\003AIC\252\002\035Agntcy.Identity.Core.V1alpha1\312\002\035Agntcy\\Identity\\Core\\V1alpha1\342\002)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Core::V1alpha1'
  _globals['_RESOLVERMETADATA']._serialized_start=115
  _globals['_RESOLVERMETADATA']._serialized_end=422
  _globals['_SERVICE']._serialized_start=424
  _globals['_SERVICE']._serialized_end=476
  _globals['_VERIFICATIONMETHOD']._serialized_start=479
  _globals['_VERIFICATIONMETHOD']._serialized_end=625
# @@protoc_insertion_point(module_scope)
