# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/core/v1alpha1/issuer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agntcy.identity.core.v1alpha1 import jwk_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_jwk__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*agntcy/identity/core/v1alpha1/issuer.proto\x12\x1d\x61gntcy.identity.core.v1alpha1\x1a\'agntcy/identity/core/v1alpha1/jwk.proto\"\xfb\x03\n\x06Issuer\x12\'\n\x0corganization\x18\x01 \x01(\tH\x00R\x0corganization\x88\x01\x01\x12.\n\x10sub_organization\x18\x02 \x01(\tH\x01R\x0fsubOrganization\x88\x01\x01\x12$\n\x0b\x63ommon_name\x18\x03 \x01(\tH\x02R\ncommonName\x88\x01\x01\x12\x1f\n\x08verified\x18\x06 \x01(\x08H\x03R\x08verified\x88\x01\x01\x12\x46\n\npublic_key\x18\x04 \x01(\x0b\x32\".agntcy.identity.core.v1alpha1.JwkH\x04R\tpublicKey\x88\x01\x01\x12H\n\x0bprivate_key\x18\x05 \x01(\x0b\x32\".agntcy.identity.core.v1alpha1.JwkH\x05R\nprivateKey\x88\x01\x01\x12O\n\tauth_type\x18\x07 \x01(\x0e\x32-.agntcy.identity.core.v1alpha1.IssuerAuthTypeH\x06R\x08\x61uthType\x88\x01\x01\x42\x0f\n\r_organizationB\x13\n\x11_sub_organizationB\x0e\n\x0c_common_nameB\x0b\n\t_verifiedB\r\n\x0b_public_keyB\x0e\n\x0c_private_keyB\x0c\n\n_auth_type*g\n\x0eIssuerAuthType\x12 \n\x1cISSUER_AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14ISSUER_AUTH_TYPE_IDP\x10\x01\x12\x19\n\x15ISSUER_AUTH_TYPE_SELF\x10\x02\x42\xa1\x02\n!com.agntcy.identity.core.v1alpha1B\x0bIssuerProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\xa2\x02\x03\x41IC\xaa\x02\x1d\x41gntcy.Identity.Core.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Core\\V1alpha1\xe2\x02)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Core::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.core.v1alpha1.issuer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.core.v1alpha1B\013IssuerProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\242\002\003AIC\252\002\035Agntcy.Identity.Core.V1alpha1\312\002\035Agntcy\\Identity\\Core\\V1alpha1\342\002)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Core::V1alpha1'
  _globals['_ISSUERAUTHTYPE']._serialized_start=628
  _globals['_ISSUERAUTHTYPE']._serialized_end=731
  _globals['_ISSUER']._serialized_start=119
  _globals['_ISSUER']._serialized_end=626
# @@protoc_insertion_point(module_scope)
