# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/core/v1alpha1/jwk.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'agntcy/identity/core/v1alpha1/jwk.proto\x12\x1d\x61gntcy.identity.core.v1alpha1\"\xb5\x03\n\x03Jwk\x12\x15\n\x03\x61lg\x18\x01 \x01(\tH\x00R\x03\x61lg\x88\x01\x01\x12\x15\n\x03kty\x18\x02 \x01(\tH\x01R\x03kty\x88\x01\x01\x12\x15\n\x03use\x18\x03 \x01(\tH\x02R\x03use\x88\x01\x01\x12\x15\n\x03kid\x18\x04 \x01(\tH\x03R\x03kid\x88\x01\x01\x12\x15\n\x03pub\x18\x05 \x01(\tH\x04R\x03pub\x88\x01\x01\x12\x17\n\x04priv\x18\x06 \x01(\tH\x05R\x04priv\x88\x01\x01\x12\x17\n\x04seed\x18\x07 \x01(\tH\x06R\x04seed\x88\x01\x01\x12\x11\n\x01\x65\x18\x08 \x01(\tH\x07R\x01\x65\x88\x01\x01\x12\x11\n\x01n\x18\t \x01(\tH\x08R\x01n\x88\x01\x01\x12\x11\n\x01\x64\x18\n \x01(\tH\tR\x01\x64\x88\x01\x01\x12\x11\n\x01p\x18\x0b \x01(\tH\nR\x01p\x88\x01\x01\x12\x11\n\x01q\x18\x0c \x01(\tH\x0bR\x01q\x88\x01\x01\x12\x13\n\x02\x64p\x18\r \x01(\tH\x0cR\x02\x64p\x88\x01\x01\x12\x13\n\x02\x64q\x18\x0e \x01(\tH\rR\x02\x64q\x88\x01\x01\x12\x13\n\x02qi\x18\x0f \x01(\tH\x0eR\x02qi\x88\x01\x01\x42\x06\n\x04_algB\x06\n\x04_ktyB\x06\n\x04_useB\x06\n\x04_kidB\x06\n\x04_pubB\x07\n\x05_privB\x07\n\x05_seedB\x04\n\x02_eB\x04\n\x02_nB\x04\n\x02_dB\x04\n\x02_pB\x04\n\x02_qB\x05\n\x03_dpB\x05\n\x03_dqB\x05\n\x03_qi\">\n\x04Jwks\x12\x36\n\x04keys\x18\x01 \x03(\x0b\x32\".agntcy.identity.core.v1alpha1.JwkR\x04keysB\x9e\x02\n!com.agntcy.identity.core.v1alpha1B\x08JwkProtoP\x01ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\xa2\x02\x03\x41IC\xaa\x02\x1d\x41gntcy.Identity.Core.V1alpha1\xca\x02\x1d\x41gntcy\\Identity\\Core\\V1alpha1\xe2\x02)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\xea\x02 Agntcy::Identity::Core::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.core.v1alpha1.jwk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.agntcy.identity.core.v1alpha1B\010JwkProtoP\001ZXgithub.com/agntcy/identity/api/server/agntcy/identity/core/v1alpha1;identity_core_sdk_go\242\002\003AIC\252\002\035Agntcy.Identity.Core.V1alpha1\312\002\035Agntcy\\Identity\\Core\\V1alpha1\342\002)Agntcy\\Identity\\Core\\V1alpha1\\GPBMetadata\352\002 Agntcy::Identity::Core::V1alpha1'
  _globals['_JWK']._serialized_start=75
  _globals['_JWK']._serialized_end=512
  _globals['_JWKS']._serialized_start=514
  _globals['_JWKS']._serialized_end=576
# @@protoc_insertion_point(module_scope)
