# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapiv3/annotations.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openapiv3 import OpenAPIv3_pb2 as openapiv3_dot_OpenAPIv3__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bopenapiv3/annotations.proto\x12\nopenapi.v3\x1a\x19openapiv3/OpenAPIv3.proto\x1a google/protobuf/descriptor.proto:O\n\x08\x64ocument\x12\x1c.google.protobuf.FileOptions\x18\xf7\x08 \x01(\x0b\x32\x14.openapi.v3.DocumentR\x08\x64ocument:T\n\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xf7\x08 \x01(\x0b\x32\x15.openapi.v3.OperationR\toperation:L\n\x06schema\x12\x1f.google.protobuf.MessageOptions\x18\xf7\x08 \x01(\x0b\x32\x12.openapi.v3.SchemaR\x06schema:N\n\x08property\x12\x1d.google.protobuf.FieldOptions\x18\xf7\x08 \x01(\x0b\x32\x12.openapi.v3.SchemaR\x08propertyB\x9b\x01\n\x0e\x63om.openapi.v3B\x10\x41nnotationsProtoP\x01Z.github.com/google/gnostic/openapiv3;openapi_v3\xa2\x02\x03OXX\xaa\x02\nOpenapi.V3\xca\x02\nOpenapi\\V3\xe2\x02\x16Openapi\\V3\\GPBMetadata\xea\x02\x0bOpenapi::V3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openapiv3.annotations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.openapi.v3B\020AnnotationsProtoP\001Z.github.com/google/gnostic/openapiv3;openapi_v3\242\002\003OXX\252\002\nOpenapi.V3\312\002\nOpenapi\\V3\342\002\026Openapi\\V3\\GPBMetadata\352\002\013Openapi::V3'
# @@protoc_insertion_point(module_scope)
