// Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/node/v1alpha1/openapi.proto

package identity_node_sdk_go

import (
	_ "github.com/google/gnostic-models/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agntcy_identity_node_v1alpha1_openapi_proto protoreflect.FileDescriptor

const file_agntcy_identity_node_v1alpha1_openapi_proto_rawDesc = "" +
	"\n" +
	"+agntcy/identity/node/v1alpha1/openapi.proto\x12\x1dagntcy.identity.node.v1alpha1\x1a\x1bopenapiv3/annotations.protoB\xfd\x01\xbaG\xa6\x01\x12p\n" +
	"\rIdentity Node\x12\rIdentity Node\"F\n" +
	"\vAgntcy Team\x12\"https://github.com/agntcy/identity\x1a\x13identity@agntcy.org2\bv1alpha1\x1a(\n" +
	"\x13http://0.0.0.0:4000\x12\x11Local environment*\x062\x02\n" +
	"\x00:\x002\x00ZQgithub.com/agntcy/identity/api/agntcy/identity/node/v1alpha1;identity_node_sdk_gob\x06proto3"

var file_agntcy_identity_node_v1alpha1_openapi_proto_goTypes = []any{}
var file_agntcy_identity_node_v1alpha1_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agntcy_identity_node_v1alpha1_openapi_proto_init() }
func file_agntcy_identity_node_v1alpha1_openapi_proto_init() {
	if File_agntcy_identity_node_v1alpha1_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_node_v1alpha1_openapi_proto_rawDesc), len(file_agntcy_identity_node_v1alpha1_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_identity_node_v1alpha1_openapi_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_node_v1alpha1_openapi_proto_depIdxs,
	}.Build()
	File_agntcy_identity_node_v1alpha1_openapi_proto = out.File
	file_agntcy_identity_node_v1alpha1_openapi_proto_goTypes = nil
	file_agntcy_identity_node_v1alpha1_openapi_proto_depIdxs = nil
}
