// Code generated by go-swagger; DO NOT EDIT.

package issuer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity/api/client/models"
)

// RegisterIssuerReader is a Reader for the RegisterIssuer structure.
type RegisterIssuerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterIssuerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterIssuerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRegisterIssuerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRegisterIssuerOK creates a RegisterIssuerOK with default headers values
func NewRegisterIssuerOK() *RegisterIssuerOK {
	return &RegisterIssuerOK{}
}

/*
RegisterIssuerOK describes a response with status code 200, with default header values.

A successful response.
*/
type RegisterIssuerOK struct {
	Payload models.V1alpha1RegisterIssuerResponse
}

// IsSuccess returns true when this register issuer o k response has a 2xx status code
func (o *RegisterIssuerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register issuer o k response has a 3xx status code
func (o *RegisterIssuerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register issuer o k response has a 4xx status code
func (o *RegisterIssuerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this register issuer o k response has a 5xx status code
func (o *RegisterIssuerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this register issuer o k response a status code equal to that given
func (o *RegisterIssuerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the register issuer o k response
func (o *RegisterIssuerOK) Code() int {
	return 200
}

func (o *RegisterIssuerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/issuer/register][%d] registerIssuerOK %s", 200, payload)
}

func (o *RegisterIssuerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/issuer/register][%d] registerIssuerOK %s", 200, payload)
}

func (o *RegisterIssuerOK) GetPayload() models.V1alpha1RegisterIssuerResponse {
	return o.Payload
}

func (o *RegisterIssuerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterIssuerDefault creates a RegisterIssuerDefault with default headers values
func NewRegisterIssuerDefault(code int) *RegisterIssuerDefault {
	return &RegisterIssuerDefault{
		_statusCode: code,
	}
}

/*
RegisterIssuerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RegisterIssuerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this register issuer default response has a 2xx status code
func (o *RegisterIssuerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this register issuer default response has a 3xx status code
func (o *RegisterIssuerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this register issuer default response has a 4xx status code
func (o *RegisterIssuerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this register issuer default response has a 5xx status code
func (o *RegisterIssuerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this register issuer default response a status code equal to that given
func (o *RegisterIssuerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the register issuer default response
func (o *RegisterIssuerDefault) Code() int {
	return o._statusCode
}

func (o *RegisterIssuerDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/issuer/register][%d] RegisterIssuer default %s", o._statusCode, payload)
}

func (o *RegisterIssuerDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/issuer/register][%d] RegisterIssuer default %s", o._statusCode, payload)
}

func (o *RegisterIssuerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RegisterIssuerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
