# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/issuer/v1alpha1/local_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agntcy.identity.core.v1alpha1 import jwk_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_jwk__pb2
from agntcy.identity.core.v1alpha1 import vc_pb2 as agntcy_dot_identity_dot_core_dot_v1alpha1_dot_vc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3agntcy/identity/issuer/v1alpha1/local_service.proto\x12\x1f\x61gntcy.identity.issuer.v1alpha1\x1a\'agntcy/identity/core/v1alpha1/jwk.proto\x1a&agntcy/identity/core/v1alpha1/vc.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc8\x01\n\x0eIssueVCRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12J\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x30.agntcy.identity.core.v1alpha1.CredentialContentR\x07\x63ontent\x12Z\n\renvelope_type\x18\x03 \x01(\x0e\x32\x35.agntcy.identity.core.v1alpha1.CredentialEnvelopeTypeR\x0c\x65nvelopeType\"U\n\x0fIssueVCResponse\x12\x42\n\x02vc\x18\x01 \x01(\x0b\x32\x32.agntcy.identity.core.v1alpha1.EnvelopedCredentialR\x02vc\"N\n\x0eKeyGenResponse\x12<\n\x07keypair\x18\x01 \x01(\x0b\x32\".agntcy.identity.core.v1alpha1.JwkR\x07keypair2\xcf\x01\n\x0cLocalService\x12Q\n\x06KeyGen\x12\x16.google.protobuf.Empty\x1a/.agntcy.identity.issuer.v1alpha1.KeyGenResponse\x12l\n\x07IssueVC\x12/.agntcy.identity.issuer.v1alpha1.IssueVCRequest\x1a\x30.agntcy.identity.issuer.v1alpha1.IssueVCResponseB\xb5\x02\n#com.agntcy.identity.issuer.v1alpha1B\x11LocalServiceProtoP\x01Z\\github.com/agntcy/identity/api/server/agntcy/identity/issuer/v1alpha1;identity_issuer_sdk_go\xa2\x02\x03\x41II\xaa\x02\x1f\x41gntcy.Identity.Issuer.V1alpha1\xca\x02\x1f\x41gntcy\\Identity\\Issuer\\V1alpha1\xe2\x02+Agntcy\\Identity\\Issuer\\V1alpha1\\GPBMetadata\xea\x02\"Agntcy::Identity::Issuer::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.issuer.v1alpha1.local_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.agntcy.identity.issuer.v1alpha1B\021LocalServiceProtoP\001Z\\github.com/agntcy/identity/api/server/agntcy/identity/issuer/v1alpha1;identity_issuer_sdk_go\242\002\003AII\252\002\037Agntcy.Identity.Issuer.V1alpha1\312\002\037Agntcy\\Identity\\Issuer\\V1alpha1\342\002+Agntcy\\Identity\\Issuer\\V1alpha1\\GPBMetadata\352\002\"Agntcy::Identity::Issuer::V1alpha1'
  _globals['_ISSUEVCREQUEST']._serialized_start=199
  _globals['_ISSUEVCREQUEST']._serialized_end=399
  _globals['_ISSUEVCRESPONSE']._serialized_start=401
  _globals['_ISSUEVCRESPONSE']._serialized_end=486
  _globals['_KEYGENRESPONSE']._serialized_start=488
  _globals['_KEYGENRESPONSE']._serialized_end=566
  _globals['_LOCALSERVICE']._serialized_start=569
  _globals['_LOCALSERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
